import { describe, expect, it } from 'vitest'
import { BasicBotController } from '../src/agents/BasicBotController'
import { planExpedition } from '../src/agents/planning/ExpeditionPlanner'
import { planLoadout, waterPolicyForState } from '../src/agents/planning/SupplyPolicy'
import { getLegalActions } from '../src/core/actions'
import { executeCommand } from '../src/core/commands'
import { createInitialGame } from '../src/core/game'
import { SPECIAL_SITE_ORDER } from '../src/core/specialSites'
import type { GameCommand, GameState } from '../src/core/types'
import { distanceToTown, SPECIAL_SITE_COUNT, zoneKey } from '../src/core/world'
import { advanceOneHour } from '../src/simulation/advanceTime'

const bots=new BasicBotController()
function action<T extends GameCommand['type']>(game:GameState,citizenId:string,type:T):Extract<GameCommand,{type:T}>{const found=getLegalActions(game,citizenId).find((candidate)=>candidate.type===type);if(!found)throw new Error(`Missing ${type}`);return found as Extract<GameCommand,{type:T}>}

describe('World Beyond 2.0',()=>{
  it('generates deterministic balanced special sites without altering discovery',()=>{const first=createInitialGame(4455,4);const second=createInitialGame(4455,4);const sites=Object.values(first.world.zones).filter((zone)=>zone.specialSite);expect(sites).toHaveLength(SPECIAL_SITE_COUNT);expect(sites.map((zone)=>zone.specialSite?.type)).toEqual(Object.values(second.world.zones).filter((zone)=>zone.specialSite).map((zone)=>zone.specialSite?.type));for(const type of SPECIAL_SITE_ORDER)expect(sites.some((zone)=>zone.specialSite?.type===type)).toBe(true);expect(sites.every((zone)=>!zone.discovered)).toBe(true)})
  it('lets multiple citizens share excavation progress and unlock a buried site',()=>{let game=createInitialGame(12,3);const zone=Object.values(game.world.zones).find((candidate)=>candidate.specialSite)!;const key=zoneKey(zone.x,zone.y);game={...game,world:{...game.world,zones:{...game.world.zones,[key]:{...zone,discovered:true,zombies:0,specialSite:{...zone.specialSite!,excavationProgress:zone.specialSite!.excavationRequired-2}}}},citizens:game.citizens.map((citizen,index)=>index<2?{...citizen,location:{type:'world' as const,x:zone.x,y:zone.y}}:citizen)};game=executeCommand(game,action(game,'c01','EXCAVATE_SPECIAL_SITE')).state;expect(game.world.zones[key].specialSite?.status).toBe('buried');game=executeCommand(game,action(game,'c02','EXCAVATE_SPECIAL_SITE')).state;expect(game.world.zones[key].specialSite?.status).toBe('accessible')})
  it('keeps special-site searching separate from ordinary zone searches',()=>{let game=createInitialGame(13,2);const zone=Object.values(game.world.zones).find((candidate)=>candidate.specialSite)!;const key=zoneKey(zone.x,zone.y);game={...game,world:{...game.world,zones:{...game.world.zones,[key]:{...zone,discovered:true,zombies:0,searchesRemaining:2,specialSite:{...zone.specialSite!,status:'accessible',hiddenLoot:['twisted_plank'],searchedBy:[]}}}},citizens:game.citizens.map((citizen,index)=>index===0?{...citizen,location:{type:'world' as const,x:zone.x,y:zone.y}}:citizen)};game=executeCommand(game,action(game,'c01','SEARCH_SPECIAL_SITE')).state;expect(game.world.zones[key].searchesRemaining).toBe(2);expect(game.world.zones[key].groundItems.some((item)=>item.type==='twisted_plank')).toBe(true);expect(game.world.zones[key].specialSite?.status).toBe('depleted')})
})

describe('Expedition planning and supply policy',()=>{
  it('plans beyond the old two-tile gate-hugging range and budgets AP refills',()=>{const game=createInitialGame(99,4);const plan=planExpedition(game,'c02')!;expect(distanceToTown(plan.target.x,plan.target.y)).toBeGreaterThanOrEqual(3);expect(plan.requiredAp).toBeGreaterThan(6);expect(plan.loadout.water||plan.loadout.food).toBe(true);expect(plan.loadout.reservedLootSlots).toBeGreaterThanOrEqual(1)})
  it('switches the well into critical conservation below one ration per survivor',()=>{let game=createInitialGame(99,40);game={...game,town:{...game.town,well:{water:20}}};expect(waterPolicyForState(game)).toBe('critical');const citizen=game.citizens[1];const loadout=planLoadout(game,citizen,'explore',10,0);expect(loadout.wellWaterAllowed).toBe(false);expect(loadout.water).toBe(false);expect(loadout.food).toBe(true)})
  it('opens a private Doggy Bag when a long expedition needs food instead of draining critical well water',()=>{let game=createInitialGame(101,4);game={...game,town:{...game.town,well:{water:1}}};const decision=bots.decide(game,'c03');expect(decision?.type).toBe('OPEN_CONTAINER')})
  it('uses the Bank as an outfitter when a dangerous weapon expedition needs shared gear',()=>{let game=createInitialGame(202,4);const police=Object.values(game.world.zones).find((zone)=>zone.specialSite?.type==='police_station')!;const key=zoneKey(police.x,police.y);game={...game,town:{...game.town,bank:{water_bomb:1,food:10},construction:{workshop:{id:'workshop',apContributed:25,completed:true},watchtower:{id:'watchtower',apContributed:12,completed:true}}},world:{...game.world,zones:{...game.world.zones,[key]:{...police,discovered:true,zombies:5,specialSite:{...police.specialSite!,status:'accessible'}}}}};const decision=bots.decide(game,'c02');expect(decision?.type).toBe('WITHDRAW_BANK_ITEM');if(decision?.type==='WITHDRAW_BANK_ITEM')expect(decision.itemType).toBe('water_bomb')})
  it('lets an hourly bot execute a real long-range expedition while AP remains the action budget',()=>{let game=createInitialGame(303,2);game={...game,world:{...game.world,zones:Object.fromEntries(Object.entries(game.world.zones).map(([key,zone])=>[key,{...zone,zombies:0}]))}};game=advanceOneHour(game,bots,'c01');const bot=game.citizens[1];expect(bot.location.type).toBe('world');if(bot.location.type==='world')expect(distanceToTown(bot.location.x,bot.location.y)).toBeGreaterThanOrEqual(3);expect(bot.daily.waterTaken||bot.home.storage.every((item)=>item.type!=='doggy_bag')).toBe(true)})
})
