import { stackBankItems } from '../../core/bank'
import type { GameCommand, GameEvent, GameState } from '../../core/types'
import { ContextRegister } from './ContextRegister'
import { BANK_SECTIONS, ItemButton, RucksackStrip } from './InventoryItems'
function bankEvent(event:GameEvent):boolean{return event.type==='ITEM_DEPOSITED'||event.type==='ITEM_WITHDRAWN'}
export function BankView({game,citizenId,legalActions,act}:{game:GameState;citizenId:string;legalActions:GameCommand[];act:(command:GameCommand|undefined)=>void}){
  const player=game.citizens.find((citizen)=>citizen.id===citizenId)??game.citizens[0];const deposits=legalActions.filter((action):action is Extract<GameCommand,{type:'DEPOSIT_ITEM'}>=>action.type==='DEPOSIT_ITEM');const withdrawals=legalActions.filter((action):action is Extract<GameCommand,{type:'WITHDRAW_BANK_ITEM'}>=>action.type==='WITHDRAW_BANK_ITEM');const stacks=stackBankItems(game.town.bank);const depositItem=(itemId:string)=>act(deposits.find((candidate)=>candidate.itemId===itemId))
  return <section className="panel screen-panel"><div className="panel-heading"><div><p className="section-kicker">Shared town storage</p><h2>The Bank</h2><p className="section-note">Click a carried cargo item to deposit it. The Town Uniform and Profession Item are locked equipment and cannot enter the Bank.</p></div><span className="panel-count">{game.town.bank.length} items</span></div><section className="town-section compact-inventory-layout"><div className="inventory-surface"><div className="inventory-heading"><h3>{player.name} · Rucksack</h3><span className="micro-stat">{player.inventory.length}/{player.inventoryCapacity} cargo · +2 equipment</span></div><RucksackStrip citizen={player} onItemClick={(item)=>depositItem(item.id)} extraTooltip={()=> 'Click to deposit in the Bank.'}/></div><div className="inventory-surface"><div className="inventory-heading"><h3>Shared Inventory</h3><span className="micro-stat">click to withdraw</span></div>{stacks.length===0?<span className="compact-empty">The Bank is empty.</span>:BANK_SECTIONS.map((section)=>{const sectionStacks=stacks.filter((stack)=>section.matches(stack.type));if(!sectionStacks.length)return null;return <section className="bank-category" key={section.id}><div className="bank-category-title">{section.label}</div><div className="stacked-item-grid">{sectionStacks.map((stack)=>{const representative=stack.items.find((item)=>withdrawals.some((action)=>action.itemId===item.id));const withdraw=representative?withdrawals.find((action)=>action.itemId===representative.id):undefined;return <ItemButton key={stack.key} type={stack.type} state={stack.state} count={stack.count} disabled={!withdraw} onClick={()=>act(withdraw)} extraTooltip={withdraw?'Click to take one exact item from this stack.':'Rucksack is full or this item cannot be taken right now.'}/>})}</div></section>})}</div></section><ContextRegister game={game} title="Bank Register" matches={bankEvent}/></section>
}
