import { useState } from 'react'
import { HOME_IMPROVEMENTS, HOME_LEVEL_ORDER, HOME_LEVELS, homeName, personalDefense } from '../../core/home'
import { itemName } from '../../core/items'
import type { GameCommand, GameEvent, GameState, HomeImprovementId, ItemInstance, ItemType } from '../../core/types'
import { ContextRegister } from './ContextRegister'
import { CombinationActionMenu, ItemActionMenu, ItemStrip } from './InventoryItems'

type HomeTab='inventory'|'upgrades'|'improvements'
function commandFor(actions:GameCommand[],type:GameCommand['type'],itemId:string):GameCommand|undefined{return actions.find((action)=>action.type===type&&'itemId'in action&&action.itemId===itemId)}
function improvementCommand(actions:GameCommand[],id:HomeImprovementId):GameCommand|undefined{return actions.find((action)=>action.type==='BUILD_HOME_IMPROVEMENT'&&action.improvementId===id)}
function corpseCommand(actions:GameCommand[],type:'DISPOSE_CORPSE_OUTSIDE'|'DISPOSE_CORPSE_WATER',targetCitizenId:string):GameCommand|undefined{return actions.find((action)=>action.type===type&&'targetCitizenId'in action&&action.targetCitizenId===targetCitizenId)}
function resourceText(resources:Partial<Record<ItemType,number>>):string{const entries=Object.entries(resources) as Array<[ItemType,number|undefined]>;return entries.length?entries.map(([type,count])=>`${itemName(type)} × ${count??0}`).join(' · '):'No materials'}
function homeRegisterEvent(event:GameEvent,citizenId:string):boolean{if(!('citizenId'in event)||event.citizenId!==citizenId)return false;return['ITEM_MOVED_TO_HOME','ITEM_MOVED_TO_RUCKSACK','CONTAINER_OPENED','ITEM_CONSUMED','ITEMS_COMBINED','HOME_UPGRADED','HOME_IMPROVEMENT_BUILT'].includes(event.type)}
function foreignHomeRegisterEvent(event:GameEvent,citizenId:string):boolean{return(event.type==='CORPSE_DISPOSED'&&event.targetCitizenId===citizenId)||(event.type==='CORPSE_REANIMATED'&&event.corpseCitizenId===citizenId)||(event.type==='CITIZEN_DIED'&&event.citizenId===citizenId)}

export function HomeView({game,citizenId,ownerCitizenId,legalActions,act,onReturnHome}:{game:GameState;citizenId:string;ownerCitizenId?:string;legalActions:GameCommand[];act:(command:GameCommand|undefined)=>void;onReturnHome?:()=>void}){
  const[tab,setTab]=useState<HomeTab>('inventory')
  const actor=game.citizens.find((citizen)=>citizen.id===citizenId)??game.citizens[0]
  const player=game.citizens.find((citizen)=>citizen.id===(ownerCitizenId??citizenId))??actor
  const visiting=player.id!==actor.id
  const upgrade=legalActions.find((action)=>action.type==='UPGRADE_HOME')
  const currentDefense=personalDefense(player,game);const structuralDefense=HOME_LEVELS[player.home.level].defense;const currentIndex=HOME_LEVEL_ORDER.indexOf(player.home.level);const nextLevel=currentIndex<HOME_LEVEL_ORDER.length-1?HOME_LEVEL_ORDER[currentIndex+1]:null;const nextDefinition=nextLevel?HOME_LEVELS[nextLevel]:null
  const defenseTooltip=`Total defense protecting this home during a breach. Structure: ${structuralDefense}. Defensive objects and installed improvements are included here.`
  if(visiting){
    const drag=corpseCommand(legalActions,'DISPOSE_CORPSE_OUTSIDE',player.id)
    const water=corpseCommand(legalActions,'DISPOSE_CORPSE_WATER',player.id)
    const disposition=player.corpseDisposition==='dragged_out'?'The body was dragged outside town.':player.corpseDisposition==='watered'?'The body was destroyed with a Water Ration.':player.home.corpseAttacked?'The corpse already reanimated during a nightly internal attack.':'No body is present in this home.'
    return <section className="panel screen-panel home-screen">
      <div className="panel-heading"><div><p className="section-kicker">Visiting {player.name}</p><h2>{homeName(player.home.level)}</h2></div><div className="home-defense-compact" title={defenseTooltip}><span>Defense</span><strong>{currentDefense}</strong></div></div>
      <div className="home-upgrade-layout"><section className="home-upgrade-next"><p className="section-kicker">{player.alive?'Citizen home':'Dead citizen home'}</p><h3>{player.name}</h3><p>{player.alive?'The resident is alive. This first visit-home pass is read-only for living citizens.':player.home.holdsBody?'The resident died in town and the body remains here. An undisposed corpse can reanimate during the next nightly attack.':disposition}</p><div className="upgrade-cost"><span>{player.home.storage.length} item{player.home.storage.length===1?'':'s'} in chest</span><span>{player.home.level.replaceAll('_',' ')}</span></div>{!player.alive&&player.home.holdsBody&&<div className="inventory-actions-block"><div className="inventory-heading"><h3>Corpse disposal</h3><span className="micro-stat">source-backed</span></div><p className="adaptation-note">Pouring water consumes 1 Water Ration. Dragging the corpse outside costs 2 AP. Either prevents this body from joining the internal corpse attack.</p><div className="home-tabs"><button disabled={!drag} onClick={()=>act(drag)}><strong>Drag outside town</strong><small>2 AP</small></button><button disabled={!water} onClick={()=>act(water)}><strong>Pour water on corpse</strong><small>1 Water Ration</small></button></div></div>}{onReturnHome&&<button className="secondary" onClick={onReturnHome}>Return to my home</button>}</section><section className="home-level-table"><div className="home-level-row header"><span>Status</span><span>Body</span><span>Defense</span><span>Chest</span></div><div className="home-level-row current"><span>{player.alive?'ALIVE':'DEAD'}</span><strong>{player.home.holdsBody?'PRESENT':'CLEAR'}</strong><span>{currentDefense}</span><span>{player.home.storage.length}/{player.home.storageCapacity}</span></div></section></div>
      <ContextRegister game={game} title={`${player.name}'s Home Register`} matches={(event)=>foreignHomeRegisterEvent(event,player.id)}/>
    </section>
  }
  const toHome=(itemId:string)=>commandFor(legalActions,'MOVE_ITEM_TO_HOME',itemId);const toRucksack=(itemId:string)=>commandFor(legalActions,'MOVE_ITEM_TO_RUCKSACK',itemId)
  const actionableItems=[...player.inventory,...player.home.storage];const itemSource=(item:ItemInstance)=>player.home.storage.some((stored)=>stored.id===item.id)?'Chest':'Rucksack'
  return <section className="panel screen-panel home-screen">
    <div className="panel-heading"><div><p className="section-kicker">{player.controller==='human'?'Your home':player.name}</p><h2>{homeName(player.home.level)}</h2></div><div className="home-defense-compact" title={defenseTooltip}><span>Defense</span><strong>{currentDefense}</strong></div></div>
    <div className="home-tabs" role="tablist" aria-label="Home view"><button className={tab==='inventory'?'active':''} aria-selected={tab==='inventory'} onClick={()=>setTab('inventory')}><strong>Inventory & Actions</strong><small>Rucksack and chest</small></button><button className={tab==='upgrades'?'active':''} aria-selected={tab==='upgrades'} onClick={()=>setTab('upgrades')}><strong>Building Upgrades</strong><small>Permanent home level</small></button><button className={tab==='improvements'?'active':''} aria-selected={tab==='improvements'} onClick={()=>setTab('improvements')}><strong>Home Improvements</strong><small>Defense and storage works</small></button></div>
    {tab==='inventory'&&<><div className="compact-home-inventory"><section className="inventory-surface"><div className="inventory-heading"><h3>Rucksack</h3><span className="micro-stat">{player.inventory.length}/{player.inventoryCapacity}</span></div><ItemStrip items={player.inventory} capacity={player.inventoryCapacity} disabledForItem={(item)=>!toHome(item.id)} onItemClick={(item)=>act(toHome(item.id))} extraTooltip={(item)=>toHome(item.id)?'Click to store in your chest.':'Chest is full or this item cannot be stored right now.'}/></section><section className="inventory-surface"><div className="inventory-heading"><h3>Chest</h3><span className="micro-stat">{player.home.storage.length}/{player.home.storageCapacity}</span></div><ItemStrip items={player.home.storage} capacity={player.home.storageCapacity} disabledForItem={(item)=>!toRucksack(item.id)} onItemClick={(item)=>act(toRucksack(item.id))} extraTooltip={(item)=>toRucksack(item.id)?'Click to pack into your rucksack.':'Rucksack is full or this item cannot be packed right now.'}/></section></div><section className="inventory-actions-block"><div className="inventory-heading"><h3>My Actions</h3><span className="micro-stat">rucksack + chest</span></div><ItemActionMenu items={actionableItems} actions={legalActions} act={act} sourceForItem={itemSource}/><CombinationActionMenu actions={legalActions} act={act}/></section></>}
    {tab==='upgrades'&&<div className="home-upgrade-layout"><section className="home-upgrade-next"><p className="section-kicker">Current level {currentIndex}</p><h3>{homeName(player.home.level)}</h3>{nextDefinition?<><p>Next: <strong>{nextDefinition.name}</strong> · defense {structuralDefense} → {nextDefinition.defense}</p><div className="upgrade-cost"><span>{nextDefinition.apCost} AP</span><span>{resourceText(nextDefinition.resources)}</span></div>{!nextDefinition.historicalMaterials&&<p className="adaptation-note">The level/AP/defense follow the Season-16 progression. Some mature material types are not modeled yet, so this tier uses explicit Live2Nite substitutions.</p>}{nextDefinition.apCost>player.maxAp&&<p className="adaptation-note">This historical tier costs more than the ordinary 6 AP cap. It remains visible now, but completing it will require future AP-boosting mechanics.</p>}<button className="primary" disabled={!upgrade} onClick={()=>act(upgrade)}>Upgrade to {nextDefinition.name}<small>{nextDefinition.apCost} AP</small></button>{player.home.upgradedDay===game.day&&<small className="home-upgrade-limit">A home may only be upgraded once per day.</small>}</>:<p className="empty-state">This home has reached Castle, the top structural tier.</p>}</section><section className="home-level-table"><div className="home-level-row header"><span>Level</span><span>Home</span><span>Defense</span><span>AP</span></div>{HOME_LEVEL_ORDER.map((level,index)=>{const def=HOME_LEVELS[level];return <div key={level} className={`home-level-row ${index===currentIndex?'current':''} ${index<currentIndex?'complete':''}`}><span>{index}</span><strong>{def.name}</strong><span>{def.defense}</span><span>{def.apCost||'—'}</span></div>})}</section></div>}
    {tab==='improvements'&&<div className="home-improvements-list"><p className="adaptation-note">Fence, Reinforcements and More Storage are reconstructed from historical Home/Hero improvements. Until the Hero system is implemented, Live2Nite temporarily exposes these supported works to ordinary citizens.</p>{(Object.keys(HOME_IMPROVEMENTS) as HomeImprovementId[]).map((id)=>{const def=HOME_IMPROVEMENTS[id];const level=player.home.improvements[id]??0;const next=level<def.maxLevel?level+1:null;const action=improvementCommand(legalActions,id);return <article className="home-improvement-card" key={id}><div><p className="section-kicker">Level {level}/{def.maxLevel}</p><h3>{def.name}</h3><p>{def.description}</p>{next!==null&&<small>{def.apCost(next)} AP · {resourceText(def.resources(next))}</small>}</div><div className="home-improvement-effect"><strong>{def.defensePerLevel?`+${def.defensePerLevel} defense / level`:`+${def.storagePerLevel} chest slot / level`}</strong>{next!==null?<button disabled={!action} onClick={()=>act(action)}>Build level {next}</button>:<span className="facility-status online">MAX</span>}</div></article>})}</div>}
    <ContextRegister game={game} title={`${player.name}'s Home Register`} matches={(event)=>homeRegisterEvent(event,player.id)}/>
  </section>
}
