import { BAREHANDED_KILL_CHANCE_PERCENT, weaponDefinition } from '../../core/combat'
import { ITEMS, itemName, itemPurpose } from '../../core/items'
import { specialSiteName, specialSitePurpose } from '../../core/specialSites'
import type { Direction, GameCommand, GameState, ItemInstance } from '../../core/types'
import { getZone, zoneControl } from '../../core/world'
import { findAction } from '../actionHelpers'
import '../expedition.css'

function itemAction(actions:GameCommand[],type:GameCommand['type'],itemId:string):GameCommand|undefined{return actions.find((action)=>action.type===type&&'itemId'in action&&action.itemId===itemId)}
function SupplyCard({item,actions,act}:{item:ItemInstance;actions:GameCommand[];act:(command:GameCommand|undefined)=>void}){const open=itemAction(actions,'OPEN_CONTAINER',item.id);const eat=itemAction(actions,'EAT_ITEM',item.id);const drink=itemAction(actions,'DRINK_ITEM',item.id);const definition=ITEMS[item.type];return <article className={`field-supply category-${definition.category}`}><div><strong>{itemName(item.type)}</strong><small>{itemPurpose(item.type)}</small></div><div>{open&&<button onClick={()=>act(open)}>Open</button>}{eat&&<button className="supply-action" onClick={()=>act(eat)}>Eat · refill AP</button>}{drink&&<button className="supply-action" onClick={()=>act(drink)}>Drink · refill AP</button>}</div></article>}

export function WorldView({game,citizenId,legalActions,currentZone,control,act,move}:{game:GameState;citizenId:string;legalActions:GameCommand[];currentZone:ReturnType<typeof getZone>;control:ReturnType<typeof zoneControl>|null;act:(command:GameCommand|undefined)=>void;move:(direction:Direction)=>void}){
  const player=game.citizens.find((citizen)=>citizen.id===citizenId)??game.citizens[0]
  if(player.location.type==='town'){const open=findAction(legalActions,'OPEN_GATE');const close=findAction(legalActions,'CLOSE_GATE');const exit=findAction(legalActions,'EXIT_TOWN');return <section className="panel screen-panel world-staging"><div className="panel-heading"><div><p className="section-kicker">Expedition planning · {player.name}</p><h2>World Beyond</h2><p className="section-note">Undepleted frontier zones and discovered ruins now provide distinct reasons to travel farther. Supplies extend AP reach but occupy valuable rucksack space.</p></div><span className={`gate-chip ${game.town.gateOpen?'open':''}`}>{game.town.gateOpen?'GATE OPEN':'GATE SEALED'}</span></div><section className="town-feature gate-card facility-hero-card"><div className="feature-icon">G</div><div className="feature-copy"><span>Town Gate</span><strong>{game.town.gateOpen?'Open':'Sealed'}</strong><p>An open gate nullifies town defense during the nightly attack.</p></div><div className="feature-actions">{open&&<button onClick={()=>act(open)}>Open <small>1 AP</small></button>}{close&&<button onClick={()=>act(close)}>Close <small>1 AP</small></button>}{exit&&<button className="primary" onClick={()=>act(exit)}>Go outside <small>0 AP</small></button>}</div></section><div className="expedition-primer"><strong>World Beyond 2.0</strong><span>Ruins are separate from ordinary desert scavenging. Clear buried entrances with shared AP, then search the site-specific loot source while ordinary zone searches remain intact.</span></div></section>}
  if(!currentZone||!control)return null
  const search=findAction(legalActions,'SEARCH_ZONE');const enter=findAction(legalActions,'ENTER_TOWN');const fists=findAction(legalActions,'ATTACK_BAREHANDED');const excavate=findAction(legalActions,'EXCAVATE_SPECIAL_SITE');const siteSearch=findAction(legalActions,'SEARCH_SPECIAL_SITE')
  const pickups=legalActions.filter((action):action is Extract<GameCommand,{type:'PICK_UP_ITEM'}>=>action.type==='PICK_UP_ITEM');const weaponActions=legalActions.filter((action):action is Extract<GameCommand,{type:'USE_WEAPON'}>=>action.type==='USE_WEAPON')
  const carriedWeapons=player.inventory.flatMap((item)=>{const definition=weaponDefinition(item.type);const command=weaponActions.find((action)=>action.itemId===item.id);return definition?[{item,definition,command}]:[]})
  const depleted=currentZone.searchesRemaining===0;const alreadyDepletedSearched=(currentZone.depletedSearchedBy??[]).includes(player.id);const site=currentZone.specialSite
  return <section className="panel screen-panel"><div className="panel-heading"><div><p className="section-kicker">World Beyond · {player.name}</p><h2>Zone [{player.location.x},{player.location.y}]</h2><p className="section-note">Ordinary search, depleted scavenging and special-site exploration are independent activities.</p></div><div className="world-heading-chips"><span className={`zone-chip ${control.trapped?'danger':''}`}>{control.trapped?'TRAPPED':'CONTROLLED'}</span><span className={`zone-chip ${depleted?'depleted-chip':''}`}>{depleted?'DEPLETED':'UNDEPLETED'}</span></div></div>
    {site&&<section className={`special-site-card status-${site.status}`}><div className="special-site-heading"><div><p className="section-kicker">Discovered ruin</p><h3>{specialSiteName(site.type)}</h3><p>{specialSitePurpose(site.type)}</p></div><span>{site.status.toUpperCase()}</span></div>{site.status==='buried'?<><div className="site-progress"><span style={{width:`${Math.round(site.excavationProgress/site.excavationRequired*100)}%`}}/></div><p>{site.excavationProgress}/{site.excavationRequired} excavation AP contributed. Multiple citizens can help clear the same entrance.</p><button disabled={!excavate} onClick={()=>act(excavate)}>Clear debris <small>1 AP</small></button></>:site.status==='accessible'?<><p>{site.hiddenLoot.length} site find(s) remain. This does not consume the zone's ordinary searches.</p><button disabled={!siteSearch} onClick={()=>act(siteSearch)}>Search the structure <small>0 AP</small></button></>:<p className="empty-state">This structure has been stripped of its special finds.</p>}</section>}
    <div className={`control ${control.trapped?'danger':''}`}><div><span>Citizens here</span><strong>{control.humans}</strong><small>{control.humanPoints} control points</small></div><div><span>Zombies</span><strong>{control.zombies}</strong><small>{control.zombiePoints} control points</small></div><p>{control.trapped?'Zombie control exceeds human control. Search, fight or wait for rescue; excavation requires control of the zone.':'Human control is sufficient to leave or work this zone.'}</p></div>
    <section className={`combat-panel ${control.trapped?'combat-urgent':''}`}><div className="section-heading-row"><div><p className="section-kicker">Zone combat</p><h3>{currentZone.zombies>0?`${currentZone.zombies} zombie${currentZone.zombies===1?'':'s'} present`:'Zone clear'}</h3></div>{currentZone.zombies>0&&<span className="micro-stat">{player.ap}/{player.maxAp} AP</span>}</div>{currentZone.zombies===0?<p className="empty-state">There are no zombies here to attack.</p>:<><p className="combat-rule">Weapons cost 0 AP but cannot be used while exhausted. Bare hands remain the risky 1 AP fallback.</p><div className="combat-actions">{carriedWeapons.map(({item,definition,command})=><button className="weapon-action" key={item.id} disabled={!command} onClick={()=>act(command)}><strong>Use {itemName(item.type)}</strong><small>{definition.minKills}–{definition.maxKills} kills · {definition.apCost} AP</small></button>)}<button className="fist-action" disabled={!fists} onClick={()=>act(fists)}><strong>Fight bare-handed</strong><small>{BAREHANDED_KILL_CHANCE_PERCENT}% kill chance · 1 AP</small></button></div></>}</section>
    <section className="world-actions-grid"><div className="movement-card"><h3>Travel</h3><div className="movement"><button disabled={!legalActions.some(a=>a.type==='MOVE'&&a.direction==='NORTH')} onClick={()=>move('NORTH')}>↑ <small>1 AP</small></button><div><button disabled={!legalActions.some(a=>a.type==='MOVE'&&a.direction==='WEST')} onClick={()=>move('WEST')}>←</button><button disabled={!legalActions.some(a=>a.type==='MOVE'&&a.direction==='SOUTH')} onClick={()=>move('SOUTH')}>↓</button><button disabled={!legalActions.some(a=>a.type==='MOVE'&&a.direction==='EAST')} onClick={()=>move('EAST')}>→</button></div></div>{enter&&<button className="primary return-button" onClick={()=>act(enter)}>Enter town <small>0 AP</small></button>}</div><div className={`search-card ${depleted?'depleted-search':''}`}><h3>{depleted?'Scavenge Depleted Zone':'Search Undepleted Zone'}</h3><p>{depleted?(alreadyDepletedSearched?'This citizen has already combed the depleted ground here.':'Low-grade Rotting Logs and Scrap Metal remain after the useful finds are gone.'):`${currentZone.searchesRemaining} normal search opportunity(s) remain.`}</p><button disabled={!search} onClick={()=>act(search)}>{depleted?'Comb the depleted ground':'Search the zone'} <small>0 AP</small></button><div className="ground-list"><h4>Visible on the ground</h4>{currentZone.groundItems.length===0?<p className="empty-state">Nothing visible.</p>:currentZone.groundItems.map((item)=>{const command=pickups.find((candidate)=>candidate.itemId===item.id);return <button key={item.id} disabled={!command} onClick={()=>act(command)}>Pick up {itemName(item.type)} <small>0 AP</small></button>})}</div></div></section>
    <section className="field-kit"><div className="section-heading-row"><div><h3>{player.name} · Field Rucksack</h3><p>Every carried supply trades one loot slot for range or safety.</p></div><span className="micro-stat">{player.inventory.length}/{player.inventoryCapacity}</span></div>{player.inventory.length===0?<p className="empty-state">Nothing carried.</p>:<div className="field-supplies">{player.inventory.map((item)=><SupplyCard key={item.id} item={item} actions={legalActions} act={act}/>)}</div>}</section>
  </section>
}
