import { removeBankItemById, removeBankItems } from './bank'
import { completionWaterBonus, revealsAllTerrain } from './construction'
import { createItemInstance } from './items'
import { zoneKey } from './world'
import type { Citizen, GameEvent, GameState, ItemInstance, ItemStorage, ItemType } from './types'

function replaceCitizen(state:GameState,citizenId:string,update:(citizen:Citizen)=>Citizen):Citizen[]{return state.citizens.map((citizen)=>citizen.id===citizenId?update(citizen):citizen)}
function removeStoredItem(citizen:Citizen,itemId:string,source:ItemStorage):Citizen{if(source==='inventory')return{...citizen,inventory:citizen.inventory.filter((item)=>item.id!==itemId)};if(source==='home')return{...citizen,home:{...citizen.home,storage:citizen.home.storage.filter((item)=>item.id!==itemId)}};return citizen}
function consumeFromItems(items:ItemInstance[],type:ItemType,count:number):{items:ItemInstance[];remaining:number}{let remaining=count;const kept:ItemInstance[]=[];for(const item of items){if(item.type===type&&remaining>0){remaining-=1;continue}kept.push(item)}return{items:kept,remaining}}
function consumePersonalResources(citizen:Citizen,resources:Partial<Record<ItemType,number>>):Citizen{let inventory=[...citizen.inventory];let storage=[...citizen.home.storage];for(const[type,amount]of Object.entries(resources)){const itemType=type as ItemType;let remaining=amount??0;const fromInventory=consumeFromItems(inventory,itemType,remaining);inventory=fromInventory.items;remaining=fromInventory.remaining;const fromStorage=consumeFromItems(storage,itemType,remaining);storage=fromStorage.items}return{...citizen,inventory,home:{...citizen.home,storage}}}
function withoutMission(state:GameState,citizenId:string):GameState['botMissions']{const next={...state.botMissions};delete next[citizenId];return next}
function missionsForNewDay(state:GameState):GameState['botMissions']{const next:GameState['botMissions']={};for(const[citizenId,mission]of Object.entries(state.botMissions)){const citizen=state.citizens.find((candidate)=>candidate.id===citizenId);if(!citizen?.alive||citizen.location.type!=='world')continue;const phase=mission.phase==='camp'?(citizen.location.x===mission.target.x&&citizen.location.y===mission.target.y?'operate':'outbound'):mission.phase;next[citizenId]={...mission,phase}}return next}
function replaceGround(state:GameState,key:string,update:(items:ItemInstance[])=>ItemInstance[]):GameState['world']{const zone=state.world.zones[key];if(!zone)return state.world;return{...state.world,zones:{...state.world.zones,[key]:{...zone,groundItems:update(zone.groundItems)}}}}
function generatedItems(state:GameState,type:ItemType,count:number):ItemInstance[]{return Array.from({length:count},(_,offset)=>createItemInstance(`i${String(state.nextItemId+offset).padStart(6,'0')}`,type))}

function reduceSingleEvent(state:GameState,event:GameEvent):GameState{
  switch(event.type){
    case 'AP_SPENT':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,ap:Math.max(0,citizen.ap-event.amount)}))}
    case 'GATE_SET':return{...state,town:{...state.town,gateOpen:event.open}}
    case 'CITIZEN_LOCATION_CHANGED':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,location:event.location,temporaryControl:null,camping:{...citizen.camping,hidden:false,survivalChance:null,hiddenDay:null},status:event.desertStep?{...citizen.status,desertStepsToday:citizen.status.desertStepsToday+1}:citizen.status}))}
    case 'CITIZEN_STATUS_CHANGED':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,status:event.status}))}
    case 'CAMP_IMPROVED':{const zone=state.world.zones[event.zoneKey];if(!zone)return state;return{...state,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:{...zone,campImprovements:Math.min(10,(zone.campImprovements??0)+event.amount)}}}}}
    case 'CAMP_IMPROVEMENTS_DECAYED':{const zone=state.world.zones[event.zoneKey];if(!zone)return state;return{...state,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:{...zone,campImprovements:Math.max(0,(zone.campImprovements??0)-event.amount)}}}}}
    case 'CITIZEN_HIDING_SET':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,camping:{...citizen.camping,hidden:event.hidden,survivalChance:event.hidden?event.survivalChance:null,hiddenDay:event.hidden?event.day:null}}))}
    case 'CAMPING_RESOLVED':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,camping:{...citizen.camping,hidden:false,survivalChance:null,hiddenDay:null,nightsSurvived:citizen.camping.nightsSurvived+(event.survived?1:0),lastSurvivedDay:event.survived?event.day:citizen.camping.lastSurvivedDay}}))}
    case 'ZONE_DISCOVERED':{const zone=state.world.zones[event.zoneKey];if(!zone||zone.discovered)return state;return{...state,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:{...zone,discovered:true}}}}}
    case 'ZONE_OBSERVED':{if(!state.world.zones[event.zoneKey])return state;return{...state,world:{...state.world,intel:{...state.world.intel,[event.zoneKey]:{observedZombies:event.zombies,lastObservedDay:event.day,lastObservedHour:event.hour??state.clock.hour}}}}}
    case 'WORLD_ZOMBIES_EVOLVED':{if(!event.changes.length)return state;const zones={...state.world.zones};for(const change of event.changes){const zone=zones[change.zoneKey];if(zone)zones[change.zoneKey]={...zone,zombies:change.after}}return{...state,world:{...state.world,zones}}}
    case 'ZONE_CONTROL_LOST':return state
    case 'TEMPORARY_CONTROL_GRANTED':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,temporaryControl:{zoneKey:event.zoneKey,grantedDay:event.day,grantedHour:event.hour??state.clock.hour}}))}
    case 'TEMPORARY_CONTROL_EXPIRED':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>citizen.temporaryControl?.zoneKey===event.zoneKey?{...citizen,temporaryControl:null}:citizen)}
    case 'ZONE_CONTROL_RESTORED':return{...state,citizens:state.citizens.map((citizen)=>citizen.temporaryControl?.zoneKey===event.zoneKey?{...citizen,temporaryControl:null}:citizen)}
    case 'ZONE_SEARCHED':{const zone=state.world.zones[event.zoneKey];if(!zone)return state;const depleted=event.mode==='depleted';const searchedBy=zone.searchedBy.includes(event.citizenId)?zone.searchedBy:[...zone.searchedBy,event.citizenId];const depletedBy=(zone.depletedSearchedBy??[]).includes(event.citizenId)?(zone.depletedSearchedBy??[]):[...(zone.depletedSearchedBy??[]),event.citizenId];const updatedZone=depleted?{...zone,depletedSearchedBy:depletedBy,groundItems:event.item?[...zone.groundItems,event.item]:zone.groundItems}:{...zone,searchesRemaining:Math.max(0,zone.searchesRemaining-1),searchedBy,hiddenLoot:zone.hiddenLoot.slice(1),groundItems:event.item?[...zone.groundItems,event.item]:zone.groundItems};return{...state,rngState:event.rngStateAfter??state.rngState,nextItemId:event.item?state.nextItemId+1:state.nextItemId,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:updatedZone}}}}
    case 'ZONE_REPLENISHED':{const zone=state.world.zones[event.zoneKey];if(!zone)return state;return{...state,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:{...zone,searchesRemaining:1,searchedBy:[],hiddenLoot:[event.loot]}}}}}
    case 'SPECIAL_SITE_EXCAVATED':{const zone=state.world.zones[event.zoneKey];const site=zone?.specialSite;if(!zone||!site)return state;const progress=Math.min(site.excavationRequired,site.excavationProgress+event.amount);return{...state,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:{...zone,specialSite:{...site,excavationProgress:progress,status:progress>=site.excavationRequired?'accessible':'buried'}}}}}}
    case 'SPECIAL_SITE_SEARCHED':{const zone=state.world.zones[event.zoneKey];const site=zone?.specialSite;if(!zone||!site)return state;const hiddenLoot=site.hiddenLoot.slice(1);const searchedBy=site.searchedBy.includes(event.citizenId)?site.searchedBy:[...site.searchedBy,event.citizenId];return{...state,nextItemId:event.item?state.nextItemId+1:state.nextItemId,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:{...zone,groundItems:event.item?[...zone.groundItems,event.item]:zone.groundItems,specialSite:{...site,hiddenLoot,searchedBy,status:hiddenLoot.length===0?'depleted':'accessible'}}}}}}
    case 'ITEM_PICKED_UP':{const zone=state.world.zones[event.zoneKey];if(!zone)return state;return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:[...citizen.inventory,event.item]})),world:replaceGround(state,event.zoneKey,(items)=>items.filter((item)=>item.id!==event.item.id))}}
    case 'ITEM_DROPPED':{const zone=state.world.zones[event.zoneKey];if(!zone)return state;return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:citizen.inventory.filter((item)=>item.id!==event.item.id)})),world:replaceGround(state,event.zoneKey,(items)=>[...items,event.item])}}
    case 'COMBAT_RESOLVED':{const zone=state.world.zones[event.zoneKey];if(!zone)return state;let citizens=state.citizens;let world=state.world;const broken=(item:ItemInstance)=>event.brokenInto?createItemInstance(item.id,event.brokenInto):item;if(event.item&&event.source==='ground'){world=replaceGround(state,event.zoneKey,(items)=>event.consumed?items.filter((item)=>item.id!==event.item?.id):event.brokenInto?items.map((item)=>item.id===event.item?.id?broken(item):item):items)}else if(event.item&&event.consumed)citizens=replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:citizen.inventory.filter((item)=>item.id!==event.item?.id)}));else if(event.item&&event.brokenInto)citizens=replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:citizen.inventory.map((item)=>item.id===event.item?.id?broken(item):item)}));const updatedZone=world.zones[event.zoneKey]??zone;return{...state,rngState:event.rngStateAfter,citizens,world:{...world,zones:{...world.zones,[event.zoneKey]:{...updatedZone,zombies:Math.max(0,updatedZone.zombies-event.kills)}}}}}
    case 'ITEM_DEPOSITED':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:citizen.inventory.filter((item)=>item.id!==event.item.id)})),town:{...state.town,bank:[...state.town.bank,event.item]}}
    case 'ITEM_WITHDRAWN':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:[...citizen.inventory,event.item]})),town:{...state.town,bank:removeBankItemById(state.town.bank,event.item.id)}}
    case 'ITEM_MOVED_TO_HOME':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:citizen.inventory.filter((item)=>item.id!==event.item.id),home:{...citizen.home,storage:[...citizen.home.storage,event.item]}}))}
    case 'ITEM_MOVED_TO_RUCKSACK':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:[...citizen.inventory,event.item],home:{...citizen.home,storage:citizen.home.storage.filter((item)=>item.id!==event.item.id)}}))}
    case 'CONTAINER_OPENED':{if(event.source==='ground'&&event.zoneKey)return{...state,rngState:event.rngStateAfter,nextItemId:state.nextItemId+1,world:replaceGround(state,event.zoneKey,(items)=>[...items.filter((item)=>item.id!==event.containerId),event.output])};return{...state,rngState:event.rngStateAfter,nextItemId:state.nextItemId+1,citizens:replaceCitizen(state,event.citizenId,(citizen)=>event.source==='inventory'?{...citizen,inventory:[...citizen.inventory.filter((item)=>item.id!==event.containerId),event.output]}:{...citizen,home:{...citizen.home,storage:[...citizen.home.storage.filter((item)=>item.id!==event.containerId),event.output]}})}}
    case 'CONSTRUCTION_KIT_OPENED':{if(event.source==='ground'&&event.zoneKey)return{...state,rngState:event.rngStateAfter,nextItemId:state.nextItemId+event.outputs.length,world:replaceGround(state,event.zoneKey,(items)=>[...items.filter((item)=>item.id!==event.containerId),...event.outputs])};return{...state,rngState:event.rngStateAfter,nextItemId:state.nextItemId+event.outputs.length,citizens:replaceCitizen(state,event.citizenId,(citizen)=>event.source==='inventory'?{...citizen,inventory:[...citizen.inventory.filter((item)=>item.id!==event.containerId),...event.outputs]}:{...citizen,home:{...citizen.home,storage:[...citizen.home.storage.filter((item)=>item.id!==event.containerId),...event.outputs]}})}}
    case 'WATER_TAKEN':return{...state,nextItemId:state.nextItemId+1,town:{...state.town,well:{water:Math.max(0,state.town.well.water-1)}},citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:[...citizen.inventory,event.item],daily:citizen.daily.waterTaken?{...citizen.daily,bonusWaterTaken:true}:{...citizen.daily,waterTaken:true}}))}
    case 'ITEM_CONSUMED':{const citizens=replaceCitizen(state,event.citizenId,(citizen)=>{const withoutItem=removeStoredItem(citizen,event.item.id,event.source);return{...withoutItem,ap:event.restoresAp?withoutItem.maxAp:withoutItem.ap,daily:event.kind==='food'?{...withoutItem.daily,ate:true}:{...withoutItem.daily,drank:true}}});const world=event.source==='ground'&&event.zoneKey?replaceGround(state,event.zoneKey,(items)=>items.filter((item)=>item.id!==event.item.id)):state.world;return{...state,citizens,world}}
    case 'HOME_UPGRADED':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>{const paid=consumePersonalResources(citizen,event.consumed);return{...paid,home:{...paid.home,level:event.to,defense:event.defenseAfter,upgradedDay:event.day}}})}
    case 'HOME_IMPROVEMENT_BUILT':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>{const paid=consumePersonalResources(citizen,event.consumed);return{...paid,home:{...paid.home,storageCapacity:event.storageCapacityAfter,improvements:{...paid.home.improvements,[event.improvementId]:event.level}}}})}
    case 'CONSTRUCTION_AP_CONTRIBUTED':{const project=state.town.construction[event.projectId];if(!project)return state;return{...state,town:{...state.town,construction:{...state.town.construction,[event.projectId]:{...project,apContributed:project.apContributed+event.amount}}}}}
    case 'CONSTRUCTION_COMPLETED':{let bank=state.town.bank;for(const[type,amount]of Object.entries(event.consumed))bank=removeBankItems(bank,type as ItemType,amount??0);const waterBonus=completionWaterBonus(event.projectId);const zones=revealsAllTerrain(event.projectId)?Object.fromEntries(Object.entries(state.world.zones).map(([key,zone])=>[key,{...zone,discovered:true}])):state.world.zones;return{...state,coordination:{commitments:state.coordination.commitments.filter((commitment)=>commitment.projectId!==event.projectId)},town:{...state.town,well:{water:state.town.well.water+waterBonus},bank,construction:{...state.town.construction,[event.projectId]:{...state.town.construction[event.projectId],completed:true}}},world:zones===state.world.zones?state.world:{...state.world,zones}}}
    case 'CONSTRUCTION_EXPIRED':{const project=state.town.construction[event.projectId];if(!project)return state;return{...state,town:{...state.town,construction:{...state.town.construction,[event.projectId]:{...project,apContributed:0,completed:false}}}}}
    case 'CONSTRUCTION_GENERATED_ITEM':{const items=generatedItems(state,event.itemType,event.amount);return{...state,nextItemId:state.nextItemId+items.length,town:{...state.town,bank:[...state.town.bank,...items]}}}
    case 'WORKSHOP_CONVERTED':{
      let bank=state.town.bank
      const inputs=event.inputs??{[event.input]:event.inputCount}
      for(const[type,count]of Object.entries(inputs))bank=removeBankItems(bank,type as ItemType,count??0)
      const outputs=generatedItems(state,event.output,event.outputCount);bank=[...bank,...outputs]
      return{...state,rngState:event.rngStateAfter??state.rngState,nextItemId:state.nextItemId+outputs.length,town:{...state.town,bank}}
    }
    case 'COORDINATION_COMMITMENT_POSTED':return{...state,coordination:{commitments:[...state.coordination.commitments.filter((commitment)=>commitment.id!==event.commitment.id&&commitment.citizenId!==event.commitment.citizenId),event.commitment]}}
    case 'COORDINATION_COMMITMENT_CLEARED':return{...state,coordination:{commitments:state.coordination.commitments.filter((commitment)=>commitment.id!==event.commitmentId)}}
    case 'BOT_MISSION_ASSIGNED':return{...state,botMissions:{...state.botMissions,[event.citizenId]:event.mission}}
    case 'BOT_MISSION_PHASE_SET':{const mission=state.botMissions[event.citizenId];if(!mission||mission.missionId!==event.missionId)return state;return{...state,botMissions:{...state.botMissions,[event.citizenId]:{...mission,phase:event.phase}}}}
    case 'BOT_MISSION_CLEARED':return{...state,botMissions:withoutMission(state,event.citizenId)}
    case 'CITIZEN_DIED':return{...state,coordination:{commitments:state.coordination.commitments.filter((commitment)=>commitment.citizenId!==event.citizenId)},botMissions:withoutMission(state,event.citizenId),citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,alive:false,ap:0,temporaryControl:null,camping:{...citizen.camping,hidden:false,survivalChance:null,hiddenDay:null}}))}
    case 'NIGHT_RESOLVED':return{...state,lastNight:event.report}
    case 'TIME_ADVANCED':return{...state,clock:{hour:event.toHour,phase:event.phase}}
    case 'DAY_STARTED':return{...state,day:event.day,clock:{hour:event.hour??1,phase:'day'},botMissions:missionsForNewDay(state),coordination:{commitments:[]},citizens:state.citizens.map((citizen)=>({...citizen,ap:citizen.alive?citizen.maxAp:0,temporaryControl:null,daily:{ate:false,drank:false,waterTaken:false},camping:{...citizen.camping,hidden:false,survivalChance:null,hiddenDay:null}}))}
  }
}
export function applyEvents(state:GameState,events:GameEvent[]):GameState{const nextState=events.reduce(reduceSingleEvent,state);return{...nextState,events:[...state.events,...events]}}
export function currentZoneKey(state:GameState,citizenId:string):string|null{const citizen=state.citizens.find((candidate)=>candidate.id===citizenId);if(!citizen||citizen.location.type!=='world')return null;return zoneKey(citizen.location.x,citizen.location.y)}
