import { bankDefenseFor } from './items'
import { zoneKey } from './world'
import type { Citizen, GameEvent, GameState, ItemStorage, ItemType } from './types'

function changeBankCount(state:GameState,type:ItemType,amount:number):GameState['town']['bank']{const current=state.town.bank[type]??0;return{...state.town.bank,[type]:Math.max(0,current+amount)}}
function replaceCitizen(state:GameState,citizenId:string,update:(citizen:Citizen)=>Citizen):Citizen[]{return state.citizens.map((citizen)=>citizen.id===citizenId?update(citizen):citizen)}
function removeStoredItem(citizen:Citizen,itemId:string,source:ItemStorage):Citizen{if(source==='inventory')return{...citizen,inventory:citizen.inventory.filter((item)=>item.id!==itemId)};return{...citizen,home:{...citizen.home,storage:citizen.home.storage.filter((item)=>item.id!==itemId)}}}
function withoutMission(state:GameState,citizenId:string):GameState['botMissions']{const next={...state.botMissions};delete next[citizenId];return next}

function reduceSingleEvent(state:GameState,event:GameEvent):GameState{
  switch(event.type){
    case 'AP_SPENT':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,ap:Math.max(0,citizen.ap-event.amount)}))}
    case 'GATE_SET':return{...state,town:{...state.town,gateOpen:event.open}}
    case 'CITIZEN_LOCATION_CHANGED':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,location:event.location}))}
    case 'ZONE_DISCOVERED':{const zone=state.world.zones[event.zoneKey];if(!zone||zone.discovered)return state;return{...state,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:{...zone,discovered:true}}}}}
    case 'ZONE_SEARCHED':{const zone=state.world.zones[event.zoneKey];if(!zone)return state;const depleted=event.mode==='depleted';const updatedZone=depleted?{...zone,depletedSearchedBy:[...(zone.depletedSearchedBy??[]),event.citizenId],groundItems:event.item?[...zone.groundItems,event.item]:zone.groundItems}:{...zone,searchesRemaining:Math.max(0,zone.searchesRemaining-1),searchedBy:[...zone.searchedBy,event.citizenId],hiddenLoot:zone.hiddenLoot.slice(1),groundItems:event.item?[...zone.groundItems,event.item]:zone.groundItems};return{...state,rngState:event.rngStateAfter??state.rngState,nextItemId:event.item?state.nextItemId+1:state.nextItemId,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:updatedZone}}}}
    case 'SPECIAL_SITE_EXCAVATED':{const zone=state.world.zones[event.zoneKey];const site=zone?.specialSite;if(!zone||!site)return state;const progress=Math.min(site.excavationRequired,site.excavationProgress+event.amount);return{...state,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:{...zone,specialSite:{...site,excavationProgress:progress,status:progress>=site.excavationRequired?'accessible':'buried'}}}}}}
    case 'SPECIAL_SITE_SEARCHED':{const zone=state.world.zones[event.zoneKey];const site=zone?.specialSite;if(!zone||!site)return state;const hiddenLoot=site.hiddenLoot.slice(1);const searchedBy=site.searchedBy.includes(event.citizenId)?site.searchedBy:[...site.searchedBy,event.citizenId];return{...state,nextItemId:event.item?state.nextItemId+1:state.nextItemId,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:{...zone,groundItems:event.item?[...zone.groundItems,event.item]:zone.groundItems,specialSite:{...site,hiddenLoot,searchedBy,status:hiddenLoot.length===0?'depleted':'accessible'}}}}}}
    case 'ITEM_PICKED_UP':{const zone=state.world.zones[event.zoneKey];if(!zone)return state;return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:[...citizen.inventory,event.item]})),world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:{...zone,groundItems:zone.groundItems.filter((item)=>item.id!==event.item.id)}}}}}
    case 'COMBAT_RESOLVED':{const zone=state.world.zones[event.zoneKey];if(!zone)return state;return{...state,rngState:event.rngStateAfter,citizens:event.consumed&&event.item?replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:citizen.inventory.filter((item)=>item.id!==event.item?.id)})):state.citizens,world:{...state.world,zones:{...state.world.zones,[event.zoneKey]:{...zone,zombies:Math.max(0,zone.zombies-event.kills)}}}}}
    case 'ITEM_DEPOSITED':{const currentCount=state.town.bank[event.item.type]??0;return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:citizen.inventory.filter((item)=>item.id!==event.item.id)})),town:{...state.town,defense:state.town.defense+bankDefenseFor(event.item.type),bank:{...state.town.bank,[event.item.type]:currentCount+1}}}}
    case 'ITEM_WITHDRAWN':{const currentCount=state.town.bank[event.item.type]??0;return{...state,nextItemId:state.nextItemId+1,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:[...citizen.inventory,event.item]})),town:{...state.town,defense:Math.max(0,state.town.defense-bankDefenseFor(event.item.type)),bank:{...state.town.bank,[event.item.type]:Math.max(0,currentCount-1)}}}}
    case 'ITEM_MOVED_TO_HOME':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:citizen.inventory.filter((item)=>item.id!==event.item.id),home:{...citizen.home,storage:[...citizen.home.storage,event.item]}}))}
    case 'ITEM_MOVED_TO_RUCKSACK':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:[...citizen.inventory,event.item],home:{...citizen.home,storage:citizen.home.storage.filter((item)=>item.id!==event.item.id)}}))}
    case 'CONTAINER_OPENED':return{...state,rngState:event.rngStateAfter,nextItemId:state.nextItemId+1,citizens:replaceCitizen(state,event.citizenId,(citizen)=>event.source==='inventory'?{...citizen,inventory:[...citizen.inventory.filter((item)=>item.id!==event.containerId),event.output]}:{...citizen,home:{...citizen.home,storage:[...citizen.home.storage.filter((item)=>item.id!==event.containerId),event.output]}})}
    case 'WATER_TAKEN':return{...state,nextItemId:state.nextItemId+1,town:{...state.town,well:{water:Math.max(0,state.town.well.water-1)}},citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,inventory:[...citizen.inventory,event.item],daily:{...citizen.daily,waterTaken:true}}))}
    case 'ITEM_CONSUMED':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>{const withoutItem=removeStoredItem(citizen,event.item.id,event.source);return{...withoutItem,ap:withoutItem.maxAp,daily:event.kind==='food'?{...withoutItem.daily,ate:true}:{...withoutItem.daily,drank:true}}})}
    case 'HOME_UPGRADED':return{...state,citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,home:{...citizen.home,level:event.to,defense:event.defenseAfter}}))}
    case 'CONSTRUCTION_AP_CONTRIBUTED':{const project=state.town.construction[event.projectId];return{...state,town:{...state.town,construction:{...state.town.construction,[event.projectId]:{...project,apContributed:project.apContributed+event.amount}}}}}
    case 'CONSTRUCTION_COMPLETED':{let bank={...state.town.bank};for(const[type,amount]of Object.entries(event.consumed)){const itemType=type as ItemType;bank={...bank,[itemType]:Math.max(0,(bank[itemType]??0)-(amount??0))}}return{...state,town:{...state.town,defense:state.town.defense+event.defenseBonus,bank,construction:{...state.town.construction,[event.projectId]:{...state.town.construction[event.projectId],completed:true}}}}}
    case 'WORKSHOP_CONVERTED':{const afterInput=changeBankCount(state,event.input,-event.inputCount);const outputCurrent=afterInput[event.output]??0;return{...state,town:{...state.town,bank:{...afterInput,[event.output]:outputCurrent+event.outputCount}}}}
    case 'BOT_MISSION_ASSIGNED':return{...state,botMissions:{...state.botMissions,[event.citizenId]:event.mission}}
    case 'BOT_MISSION_PHASE_SET':{const mission=state.botMissions[event.citizenId];if(!mission||mission.missionId!==event.missionId)return state;return{...state,botMissions:{...state.botMissions,[event.citizenId]:{...mission,phase:event.phase}}}}
    case 'BOT_MISSION_CLEARED':return{...state,botMissions:withoutMission(state,event.citizenId)}
    case 'CITIZEN_DIED':return{...state,botMissions:withoutMission(state,event.citizenId),citizens:replaceCitizen(state,event.citizenId,(citizen)=>({...citizen,alive:false,ap:0}))}
    case 'NIGHT_RESOLVED':return{...state,lastNight:event.report}
    case 'TIME_ADVANCED':return{...state,clock:{hour:event.toHour,phase:event.phase}}
    case 'DAY_STARTED':return{...state,day:event.day,clock:{hour:event.hour??1,phase:'day'},botMissions:{},citizens:state.citizens.map((citizen)=>({...citizen,ap:citizen.alive?citizen.maxAp:0,daily:{ate:false,drank:false,waterTaken:false}}))}
  }
}
export function applyEvents(state:GameState,events:GameEvent[]):GameState{const nextState=events.reduce(reduceSingleEvent,state);return{...nextState,events:[...state.events,...events]}}
export function currentZoneKey(state:GameState,citizenId:string):string|null{const citizen=state.citizens.find((candidate)=>candidate.id===citizenId);if(!citizen||citizen.location.type!=='world')return null;return zoneKey(citizen.location.x,citizen.location.y)}
