import type { ItemDisplayCategory, ItemType } from './itemCatalog'

export type ItemImplementationStatus='implemented'|'partial'|'wip'

export interface ItemSourceCatalogEntry {
  /** Live2Nite-owned semantic catalogue identity. Never an upstream numeric/prototype ID. */
  id:string
  name:string
  category:ItemDisplayCategory
  /** External source key retained only for parity/audit mapping; it is not a runtime identity. */
  sourceRef:string
  heavy:boolean
  decoration:number
  watchPoints:number
  /** Existing Live2Nite runtime identity when this source item/state is represented. */
  runtimeType:ItemType|null
  implementation:ItemImplementationStatus
}

/**
 * Complete MyHordes item/state registry from the pinned generated 5.1.1 source snapshot.
 *
 * The upstream registry contains 383 entries across the eight source categories.
 * Live2Nite uses its own semantic catalogue IDs and runtime ItemType identities; upstream
 * numerical IDs are intentionally not retained here.
 *
 * WIP records are Codex/reference metadata only. Presence in this catalogue must never make
 * an item spawnable, usable, openable, or otherwise reachable in gameplay.
 */
export const ITEM_SOURCE_CATALOG:readonly ItemSourceCatalogEntry[]=[
  {id:"water_ration",name:"Water Ration",category:"food",sourceRef:"water_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"water_ration",implementation:"implemented"},
  {id:"battery",name:"Battery",category:"resources",sourceRef:"pile_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"battery",implementation:"implemented"},
  {id:"can",name:"Can",category:"food",sourceRef:"can_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"can",implementation:"implemented"},
  {id:"open_can",name:"Open Can",category:"food",sourceRef:"can_open_#00",heavy:false,decoration:0,watchPoints:2,runtimeType:"open_can",implementation:"implemented"},
  {id:"battery_launcher_1_itf_loaded",name:"Battery Launcher 1-ITF (loaded)",category:"armoury",sourceRef:"pilegun_#00",heavy:false,decoration:0,watchPoints:8,runtimeType:"battery_launcher",implementation:"implemented"},
  {id:"taser",name:"Taser",category:"armoury",sourceRef:"taser_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:null,implementation:"wip"},
  {id:"aqua_splash_empty",name:"Aqua-Splash (empty)",category:"armoury",sourceRef:"watergun_opt_empty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"electric_whisk_loaded",name:"Electric Whisk (loaded)",category:"armoury",sourceRef:"mixergun_#00",heavy:false,decoration:0,watchPoints:18,runtimeType:null,implementation:"wip"},
  {id:"chainsaw_loaded",name:"Chainsaw (loaded)",category:"armoury",sourceRef:"chainsaw_#00",heavy:true,decoration:0,watchPoints:30,runtimeType:null,implementation:"wip"},
  {id:"lawnmower",name:"Lawnmower",category:"armoury",sourceRef:"lawn_#00",heavy:true,decoration:0,watchPoints:20,runtimeType:null,implementation:"wip"},
  {id:"adjustable_spanner",name:"Adjustable Spanner",category:"armoury",sourceRef:"wrench_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:"adjustable_spanner",implementation:"implemented"},
  {id:"screwdriver",name:"Screwdriver",category:"armoury",sourceRef:"screw_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:"screwdriver",implementation:"implemented"},
  {id:"staff",name:"Staff",category:"armoury",sourceRef:"staff_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:"staff",implementation:"implemented"},
  {id:"serrated_knife",name:"Serrated Knife",category:"armoury",sourceRef:"knife_#00",heavy:false,decoration:0,watchPoints:10,runtimeType:"serrated_knife",implementation:"implemented"},
  {id:"machete",name:"Machete",category:"armoury",sourceRef:"cutcut_#00",heavy:false,decoration:0,watchPoints:15,runtimeType:"machete",implementation:"implemented"},
  {id:"pathetic_penknife",name:"Pathetic Penknife",category:"armoury",sourceRef:"small_knife_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:"pathetic_penknife",implementation:"implemented"},
  {id:"swiss_army_knife",name:"Swiss Army Knife",category:"armoury",sourceRef:"swiss_knife_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:"swiss_army_knife",implementation:"implemented"},
  {id:"box_cutter",name:"Box Cutter",category:"armoury",sourceRef:"cutter_#00",heavy:false,decoration:0,watchPoints:7,runtimeType:"box_cutter",implementation:"implemented"},
  {id:"shopping_trolley",name:"Shopping Trolley",category:"containers",sourceRef:"cart_#00",heavy:true,decoration:0,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"can_opener",name:"Can Opener",category:"armoury",sourceRef:"can_opener_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:"can_opener",implementation:"implemented"},
  {id:"manbag",name:"Manbag",category:"containers",sourceRef:"bag_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"box_of_matches",name:"Box of Matches",category:"miscellaneous",sourceRef:"lights_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"box_of_matches",implementation:"implemented"},
  {id:"valium_shot",name:"Valium Shot",category:"pharmacy",sourceRef:"xanax_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"valium_shot",implementation:"implemented"},
  {id:"rocking_chair",name:"Rocking Chair",category:"furniture",sourceRef:"chair_#00",heavy:true,decoration:5,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"dusty_book",name:"Dusty Book",category:"miscellaneous",sourceRef:"rp_book_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"mattress",name:"Mattress",category:"defences",sourceRef:"bed_#00",heavy:true,decoration:3,watchPoints:20,runtimeType:null,implementation:"wip"},
  {id:"bedside_lamp",name:"Bedside Lamp",category:"furniture",sourceRef:"lamp_#00",heavy:false,decoration:1,watchPoints:5,runtimeType:null,implementation:"wip"},
  {id:"persian_rug",name:"Persian Rug",category:"furniture",sourceRef:"carpet_#00",heavy:true,decoration:10,watchPoints:8,runtimeType:null,implementation:"wip"},
  {id:"mini_hi_fi_broken",name:"Mini HI-Fi (Broken)",category:"furniture",sourceRef:"music_part_#00",heavy:true,decoration:1,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"padlock_and_chain",name:"Padlock and Chain",category:"furniture",sourceRef:"lock_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"doormat",name:"Doormat",category:"furniture",sourceRef:"door_carpet_#00",heavy:false,decoration:5,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"dice",name:"Dice",category:"miscellaneous",sourceRef:"dice_#00",heavy:false,decoration:0,watchPoints:-10,runtimeType:null,implementation:"wip"},
  {id:"engine",name:"Engine",category:"miscellaneous",sourceRef:"engine_#00",heavy:true,decoration:0,watchPoints:30,runtimeType:"engine",implementation:"partial"},
  {id:"belt",name:"Belt",category:"resources",sourceRef:"courroie_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"belt",implementation:"implemented"},
  {id:"handful_of_nuts_and_bolts",name:"Handful of nuts and bolts",category:"resources",sourceRef:"meca_parts_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"nuts_and_bolts",implementation:"implemented"},
  {id:"chicken",name:"Chicken",category:"miscellaneous",sourceRef:"pet_chick_#00",heavy:false,decoration:0,watchPoints:8,runtimeType:"chicken",implementation:"partial"},
  {id:"stinking_pig",name:"Stinking Pig",category:"miscellaneous",sourceRef:"pet_pig_#00",heavy:true,decoration:0,watchPoints:25,runtimeType:null,implementation:"wip"},
  {id:"giant_rat",name:"Giant Rat",category:"miscellaneous",sourceRef:"pet_rat_#00",heavy:false,decoration:0,watchPoints:12,runtimeType:null,implementation:"wip"},
  {id:"guard_dog",name:"Guard Dog",category:"defences",sourceRef:"pet_dog_#00",heavy:false,decoration:0,watchPoints:25,runtimeType:null,implementation:"wip"},
  {id:"fat_cat",name:"Fat Cat",category:"furniture",sourceRef:"pet_cat_#00",heavy:false,decoration:5,watchPoints:12,runtimeType:null,implementation:"wip"},
  {id:"huge_snake_ophiophagus_trouser",name:"Huge Snake (Ophiophagus trouser)",category:"miscellaneous",sourceRef:"pet_snake_#00",heavy:true,decoration:0,watchPoints:25,runtimeType:null,implementation:"wip"},
  {id:"pocket_vibrator_charged",name:"Pocket Vibrator (charged)",category:"miscellaneous",sourceRef:"vibr_#00",heavy:false,decoration:0,watchPoints:-10,runtimeType:null,implementation:"wip"},
  {id:"anabolic_steroids",name:"Anabolic Steroids",category:"pharmacy",sourceRef:"drug_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"anabolic_steroids",implementation:"implemented"},
  {id:"tasty_looking_steak",name:"Tasty-looking Steak",category:"food",sourceRef:"meat_#00",heavy:false,decoration:0,watchPoints:4,runtimeType:"tasty_looking_steak",implementation:"implemented"},
  {id:"unspecified_meat",name:"Unspecified Meat",category:"food",sourceRef:"undef_#00",heavy:false,decoration:0,watchPoints:2,runtimeType:null,implementation:"wip"},
  {id:"groundsheet",name:"Groundsheet",category:"miscellaneous",sourceRef:"sheet_#00",heavy:false,decoration:0,watchPoints:10,runtimeType:null,implementation:"wip"},
  {id:"ultra_rucksack",name:"Ultra-Rucksack",category:"containers",sourceRef:"bagxl_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"full_jerrycan",name:"Full Jerrycan",category:"miscellaneous",sourceRef:"jerrycan_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"twisted_plank",name:"Twisted Plank",category:"resources",sourceRef:"wood2_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"twisted_plank",implementation:"implemented"},
  {id:"wrought_iron",name:"Wrought Iron",category:"resources",sourceRef:"metal_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"wrought_iron",implementation:"implemented"},
  {id:"water_bomb",name:"Water Bomb",category:"armoury",sourceRef:"grenade_#00",heavy:false,decoration:0,watchPoints:8,runtimeType:"water_bomb",implementation:"implemented"},
  {id:"sheet_metal",name:"Sheet Metal",category:"defences",sourceRef:"plate_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"sheet_metal",implementation:"implemented"},
  {id:"jerrycan_gun_unattached",name:"Jerrycan Gun (unattached)",category:"miscellaneous",sourceRef:"jerrygun_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bandage",name:"Bandage",category:"pharmacy",sourceRef:"bandage_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"bandage",implementation:"implemented"},
  {id:"green_beer_bottle",name:"Green Beer Bottle",category:"food",sourceRef:"vodka_de_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"jerrycan_gun_empty",name:"Jerrycan Gun (empty)",category:"armoury",sourceRef:"jerrygun_off_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"retro_overhead_projector",name:"Retro Overhead Projector",category:"armoury",sourceRef:"cinema_#00",heavy:true,decoration:0,watchPoints:10,runtimeType:null,implementation:"wip"},
  {id:"semtex",name:"Semtex",category:"resources",sourceRef:"explo_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"semtex",implementation:"implemented"},
  {id:"human_flesh",name:"Human Flesh",category:"food",sourceRef:"hmeat_#00",heavy:false,decoration:0,watchPoints:15,runtimeType:"human_flesh",implementation:"partial"},
  {id:"plastic_bag",name:"Plastic Bag",category:"armoury",sourceRef:"grenade_empty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"plastic_bag",implementation:"implemented"},
  {id:"exploding_water_bomb",name:"Exploding Water Bomb",category:"armoury",sourceRef:"bgrenade_#00",heavy:false,decoration:0,watchPoints:20,runtimeType:null,implementation:"wip"},
  {id:"plastic_bag_and_semtex",name:"Plastic Bag and Semtex",category:"armoury",sourceRef:"bgrenade_empty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"incomplete_chainsaw",name:"Incomplete Chainsaw",category:"miscellaneous",sourceRef:"chainsaw_part_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"electric_whisk_incomplete",name:"Electric Whisk (incomplete)",category:"miscellaneous",sourceRef:"mixergun_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"duct_tape",name:"Duct Tape",category:"resources",sourceRef:"rustine_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"duct_tape",implementation:"implemented"},
  {id:"dismantled_mower",name:"Dismantled Mower",category:"miscellaneous",sourceRef:"lawn_part_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"copper_pipe",name:"Copper Pipe",category:"resources",sourceRef:"tube_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"copper_pipe",implementation:"implemented"},
  {id:"wonky_shopping_trolley",name:"Wonky Shopping Trolley",category:"miscellaneous",sourceRef:"cart_part_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"utility_belt",name:"Utility Belt",category:"containers",sourceRef:"pocket_belt_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"twinoid_500mg",name:"Twinoid 500mg",category:"pharmacy",sourceRef:"drug_hero_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"metal_chest",name:"Metal Chest",category:"containers",sourceRef:"chest_#00",heavy:true,decoration:0,watchPoints:8,runtimeType:"metal_chest",implementation:"implemented"},
  {id:"large_metal_chest",name:"Large Metal Chest",category:"containers",sourceRef:"chest_xl_#00",heavy:true,decoration:0,watchPoints:10,runtimeType:"xl_chest",implementation:"implemented"},
  {id:"toolbox",name:"Toolbox",category:"containers",sourceRef:"chest_tools_#00",heavy:true,decoration:0,watchPoints:5,runtimeType:"toolbox",implementation:"implemented"},
  {id:"bedside_lamp_on",name:"Bedside Lamp (on)",category:"furniture",sourceRef:"lamp_on_#00",heavy:false,decoration:3,watchPoints:5,runtimeType:null,implementation:"wip"},
  {id:"mini_hi_fi_on",name:"Mini Hi-Fi (on)",category:"furniture",sourceRef:"music_#00",heavy:true,decoration:10,watchPoints:-30,runtimeType:null,implementation:"wip"},
  {id:"pharmaceutical_products",name:"Pharmaceutical Products",category:"pharmacy",sourceRef:"pharma_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"pharmaceutical_products",implementation:"implemented"},
  {id:"sheet_metal_parts",name:"Sheet Metal (parts)",category:"miscellaneous",sourceRef:"plate_raw_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"sheet_metal_bits",implementation:"implemented"},
  {id:"wake_the_dead",name:"“Wake The Dead”",category:"food",sourceRef:"rhum_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"wake_the_dead",implementation:"implemented"},
  {id:"bloody_hot_coffee",name:"Bloody Hot Coffee",category:"food",sourceRef:"coffee_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"cafetiere",name:"Cafetière",category:"furniture",sourceRef:"coffee_machine_#00",heavy:true,decoration:5,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"incomplete_cafetiere",name:"Incomplete Cafetière",category:"miscellaneous",sourceRef:"coffee_machine_part_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"electronic_component",name:"Electronic component",category:"resources",sourceRef:"electro_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"electronic_component",implementation:"implemented"},
  {id:"citizen_s_welcome_pack",name:"Citizen's Welcome Pack",category:"containers",sourceRef:"chest_citizen_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"citizen_welcome_pack",implementation:"partial"},
  {id:"hydratone_100mg",name:"Hydratone 100mg",category:"pharmacy",sourceRef:"drug_water_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"radio_cassette_player_no_battery",name:"Radio Cassette Player (no battery)",category:"miscellaneous",sourceRef:"radio_off_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"radio_cassette_player_off",implementation:"implemented"},
  {id:"radio_cassette_player",name:"Radio Cassette Player",category:"furniture",sourceRef:"radio_on_#00",heavy:false,decoration:2,watchPoints:-15,runtimeType:"working_radio",implementation:"partial"},
  {id:"cyanide",name:"Cyanide",category:"pharmacy",sourceRef:"cyanure_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"old_door",name:"Old Door",category:"defences",sourceRef:"door_#00",heavy:true,decoration:0,watchPoints:15,runtimeType:"old_door",implementation:"implemented"},
  {id:"suspicious_looking_vegetable",name:"Suspicious-looking Vegetable",category:"food",sourceRef:"vegetable_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"vegetable",implementation:"implemented"},
  {id:"repair_kit_damaged",name:"Repair Kit (damaged)",category:"miscellaneous",sourceRef:"repair_kit_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"repair_kit",name:"Repair Kit",category:"miscellaneous",sourceRef:"repair_kit_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"repair_kit",implementation:"implemented"},
  {id:"water_pistol_empty",name:"Water Pistol (empty)",category:"armoury",sourceRef:"watergun_empty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"water_pistol",implementation:"implemented"},
  {id:"aqua_splash_3_shots",name:"Aqua-Splash (3 shots)",category:"armoury",sourceRef:"watergun_opt_3_#00",heavy:false,decoration:0,watchPoints:6,runtimeType:null,implementation:"wip"},
  {id:"aqua_splash_2_shots",name:"Aqua-Splash (2 shots)",category:"armoury",sourceRef:"watergun_opt_2_#00",heavy:false,decoration:0,watchPoints:4,runtimeType:null,implementation:"wip"},
  {id:"aqua_splash_1_shot",name:"Aqua-Splash (1 shot)",category:"armoury",sourceRef:"watergun_opt_1_#00",heavy:false,decoration:0,watchPoints:2,runtimeType:null,implementation:"wip"},
  {id:"electric_whisk_no_battery",name:"Electric Whisk (no battery)",category:"armoury",sourceRef:"mixergun_empty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"chainsaw_empty",name:"Chainsaw (empty)",category:"armoury",sourceRef:"chainsaw_empty_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"battery_launcher_1_itf_empty",name:"Battery Launcher 1-ITF (empty)",category:"armoury",sourceRef:"pilegun_empty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"battery_launcher",implementation:"implemented"},
  {id:"taser_incomplete",name:"Taser (incomplete)",category:"armoury",sourceRef:"taser_empty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"ems_system_incomplete",name:"EMS System (incomplete)",category:"miscellaneous",sourceRef:"sport_elec_empty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"ems_system_empty",implementation:"implemented"},
  {id:"ems_system_charged",name:"EMS System (charged)",category:"miscellaneous",sourceRef:"sport_elec_#00",heavy:false,decoration:0,watchPoints:-10,runtimeType:"ems_system_charged",implementation:"implemented"},
  {id:"devastator_empty",name:"Devastator (empty)",category:"armoury",sourceRef:"big_pgun_empty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"devastator_loaded",name:"Devastator (loaded)",category:"armoury",sourceRef:"big_pgun_#00",heavy:false,decoration:0,watchPoints:11,runtimeType:null,implementation:"wip"},
  {id:"devastator_incomplete",name:"Devastator (incomplete)",category:"miscellaneous",sourceRef:"big_pgun_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"radius_radar_beacon",name:"Radius Radar Beacon",category:"miscellaneous",sourceRef:"tagger_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"spy_flare",name:"Spy Flare",category:"miscellaneous",sourceRef:"flare_#00",heavy:false,decoration:0,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"jerrycan_gun_ready",name:"Jerrycan Gun (ready)",category:"armoury",sourceRef:"jerrygun_#00",heavy:false,decoration:0,watchPoints:20,runtimeType:null,implementation:"wip"},
  {id:"ektorp_gluten_chair",name:"Ektorp-Gluten Chair",category:"furniture",sourceRef:"chair_basic_#00",heavy:true,decoration:2,watchPoints:10,runtimeType:"ektorp_gluten_chair",implementation:"implemented"},
  {id:"revolver_unloaded",name:"Revolver (unloaded)",category:"furniture",sourceRef:"gun_#00",heavy:false,decoration:5,watchPoints:-20,runtimeType:null,implementation:"wip"},
  {id:"assault_rifle_unloaded",name:"Assault Rifle (unloaded)",category:"furniture",sourceRef:"machine_gun_#00",heavy:false,decoration:15,watchPoints:-25,runtimeType:null,implementation:"wip"},
  {id:"compact_detonator",name:"Compact detonator",category:"resources",sourceRef:"deto_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"compact_detonator",implementation:"implemented"},
  {id:"bag_of_cement",name:"Bag of Cement",category:"miscellaneous",sourceRef:"concrete_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"bag_of_cement",implementation:"implemented"},
  {id:"unshaped_concrete_blocks",name:"Unshaped Concrete Blocks",category:"defences",sourceRef:"concrete_wall_#00",heavy:true,decoration:0,watchPoints:17,runtimeType:"unshaped_concrete_block",implementation:"implemented"},
  {id:"unlabelled_drug",name:"Unlabelled Drug",category:"pharmacy",sourceRef:"drug_random_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"paracetoid_7g",name:"Paracetoid 7g",category:"pharmacy",sourceRef:"disinfect_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"paracetoid",implementation:"implemented"},
  {id:"ness_quick_weedkiller",name:"Ness-Quick Weedkiller",category:"miscellaneous",sourceRef:"digger_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"food_parcel",name:"Food Parcel",category:"food",sourceRef:"chest_food_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"food_box",implementation:"implemented"},
  {id:"doggy_bag",name:"Doggy Bag",category:"food",sourceRef:"food_bag_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"doggy_bag",implementation:"implemented"},
  {id:"packet_of_soft_crisps",name:"Packet of Soft Crisps",category:"food",sourceRef:"food_bar1_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"soft_crisps",implementation:"implemented"},
  {id:"mouldy_twinkies",name:"Mouldy Twinkies",category:"food",sourceRef:"food_bar2_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"mouldy_twinkies",implementation:"implemented"},
  {id:"dried_chewing_gum",name:"Dried Chewing Gum",category:"food",sourceRef:"food_bar3_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"dried_chewing_gum",implementation:"implemented"},
  {id:"rancid_shortbread_pack",name:"Rancid Shortbread Pack",category:"food",sourceRef:"food_biscuit_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"rancid_shortbread_pack",implementation:"implemented"},
  {id:"half_eaten_chicken_wings",name:"Half-eaten Chicken Wings",category:"food",sourceRef:"food_chick_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"half_eaten_chicken_wings",implementation:"implemented"},
  {id:"out_of_date_jaffa_cakes",name:"Out-of-Date Jaffa Cakes",category:"food",sourceRef:"food_pims_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"out_of_date_jaffa_cakes",implementation:"implemented"},
  {id:"stale_tart",name:"Stale Tart",category:"food",sourceRef:"food_tarte_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"stale_tart",implementation:"implemented"},
  {id:"mouldy_ham_sandwich",name:"Mouldy Ham Sandwich",category:"food",sourceRef:"food_sandw_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"food",implementation:"implemented"},
  {id:"chinese_noodles",name:"Chinese Noodles",category:"food",sourceRef:"food_noodles_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"chinese_noodles",implementation:"implemented"},
  {id:"strong_spices",name:"Strong Spices",category:"miscellaneous",sourceRef:"spices_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"strong_spices",implementation:"implemented"},
  {id:"spicy_chinese_noodles",name:"Spicy Chinese Noodles",category:"food",sourceRef:"food_noodles_hot_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"spicy_chinese_noodles",implementation:"implemented"},
  {id:"incomplete_deck_of_cards",name:"Incomplete Deck of Cards",category:"miscellaneous",sourceRef:"cards_#00",heavy:false,decoration:0,watchPoints:-10,runtimeType:null,implementation:"wip"},
  {id:"box_of_games",name:"Box of Games",category:"containers",sourceRef:"game_box_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"aqua_splash_incomplete",name:"Aqua-Splash (incomplete)",category:"miscellaneous",sourceRef:"watergun_opt_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"pocket_vibrator_incomplete",name:"Pocket Vibrator (incomplete)",category:"miscellaneous",sourceRef:"vibr_empty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"meaty_bone",name:"Meaty Bone",category:"food",sourceRef:"bone_meat_#00",heavy:false,decoration:0,watchPoints:10,runtimeType:"meaty_bone",implementation:"partial"},
  {id:"broken_human_bone",name:"Broken Human Bone",category:"armoury",sourceRef:"bone_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:"broken_human_bone",implementation:"implemented"},
  {id:"patchwork_beam",name:"Patchwork Beam",category:"resources",sourceRef:"wood_beam_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"patchwork_beam",implementation:"implemented"},
  {id:"metal_support",name:"Metal Support",category:"resources",sourceRef:"metal_beam_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"metal_support",implementation:"implemented"},
  {id:"scrap_metal",name:"Scrap Metal",category:"resources",sourceRef:"metal_bad_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"scrap_metal",implementation:"implemented"},
  {id:"rotting_log",name:"Rotting Log",category:"resources",sourceRef:"wood_bad_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"rotten_log",implementation:"implemented"},
  {id:"hacksaw",name:"Hacksaw",category:"miscellaneous",sourceRef:"saw_tool_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"saw_tool",implementation:"implemented"},
  {id:"quality_log",name:"Quality Log",category:"furniture",sourceRef:"wood_log_#00",heavy:true,decoration:2,watchPoints:0,runtimeType:"quality_log",implementation:"implemented"},
  {id:"broken_electronic_device",name:"Broken Electronic Device",category:"resources",sourceRef:"electro_box_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"broken_electronic_device",implementation:"implemented"},
  {id:"flatpacked_furniture",name:"Flatpacked Furniture",category:"miscellaneous",sourceRef:"deco_box_#00",heavy:true,decoration:0,watchPoints:15,runtimeType:"decoration_box",implementation:"implemented"},
  {id:"damaged_hacksaw",name:"Damaged Hacksaw",category:"miscellaneous",sourceRef:"saw_tool_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"saw_tool_part",implementation:"implemented"},
  {id:"mechanism",name:"Mechanism",category:"resources",sourceRef:"mecanism_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"mechanism",implementation:"implemented"},
  {id:"trestle",name:"Trestle",category:"defences",sourceRef:"trestle_#00",heavy:true,decoration:1,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"jarpen_table",name:"Järpen Table",category:"defences",sourceRef:"table_#00",heavy:true,decoration:3,watchPoints:15,runtimeType:"table",implementation:"partial"},
  {id:"water_purifying_tablets",name:"Water Purifying Tablets",category:"pharmacy",sourceRef:"water_cleaner_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"intestine_melon",name:"Intestine Melon",category:"food",sourceRef:"vegetable_tasty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"flash_powder",name:"Flash Powder",category:"miscellaneous",sourceRef:"powder_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"flash_grenade",name:"Flash Grenade",category:"miscellaneous",sourceRef:"flash_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:null,implementation:"wip"},
  {id:"teddy_bear",name:"Teddy Bear",category:"furniture",sourceRef:"teddy_#00",heavy:false,decoration:8,watchPoints:-15,runtimeType:null,implementation:"wip"},
  {id:"crate_lid",name:"Crate Lid",category:"miscellaneous",sourceRef:"wood_plate_part_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"solid_wooden_board",name:"Solid Wooden Board",category:"defences",sourceRef:"wood_plate_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"wad_of_cash",name:"Wad of Cash",category:"furniture",sourceRef:"money_#00",heavy:false,decoration:7,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"tool_bag",name:"Tool Bag",category:"miscellaneous",sourceRef:"repair_kit_part_raw_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"tool_bag",implementation:"implemented"},
  {id:"radius_mark_ii_incomplete",name:"Radius Mark II (incomplete)",category:"miscellaneous",sourceRef:"radius_mk2_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"radius_mark_ii",name:"Radius Mark II",category:"miscellaneous",sourceRef:"radius_mk2_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"kwik_fix",name:"Kwik-fix",category:"miscellaneous",sourceRef:"repair_one_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"kwik_fix",implementation:"implemented"},
  {id:"engine_incomplete",name:"Engine (incomplete)",category:"miscellaneous",sourceRef:"engine_part_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"engine_incomplete",implementation:"implemented"},
  {id:"old_washing_machine",name:"Old Washing Machine",category:"furniture",sourceRef:"machine_1_#00",heavy:true,decoration:2,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"carcinogenic_oven",name:"Carcinogenic Oven",category:"furniture",sourceRef:"machine_2_#00",heavy:true,decoration:2,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"beer_fridge",name:"Beer Fridge",category:"furniture",sourceRef:"machine_3_#00",heavy:true,decoration:2,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"a_letter_with_no_address",name:"A letter with no address",category:"miscellaneous",sourceRef:"rp_letter_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"scroll",name:"Scroll",category:"miscellaneous",sourceRef:"rp_scroll_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"instruction_manual",name:"Instruction Manual",category:"miscellaneous",sourceRef:"rp_manual_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"illegible_notebook",name:"Illegible Notebook",category:"miscellaneous",sourceRef:"rp_book2_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"photo_album",name:"Photo Album",category:"miscellaneous",sourceRef:"rp_book_#01",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"stack_of_papers",name:"Stack of Papers",category:"miscellaneous",sourceRef:"rp_sheets_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"rusty_chain",name:"Rusty Chain",category:"armoury",sourceRef:"chain_#00",heavy:false,decoration:0,watchPoints:7,runtimeType:"chain",implementation:"implemented"},
  {id:"dodgy_homemade_dish",name:"Dodgy Homemade Dish",category:"food",sourceRef:"dish_#00",heavy:false,decoration:0,watchPoints:4,runtimeType:null,implementation:"wip"},
  {id:"tasty_homemade_dish",name:"Tasty Homemade Dish",category:"food",sourceRef:"dish_tasty_#00",heavy:false,decoration:0,watchPoints:6,runtimeType:null,implementation:"wip"},
  {id:"iron_chest",name:"Iron Chest",category:"furniture",sourceRef:"home_box_xl_#00",heavy:true,decoration:0,watchPoints:8,runtimeType:null,implementation:"wip"},
  {id:"boxes",name:"Boxes",category:"furniture",sourceRef:"home_box_#00",heavy:false,decoration:0,watchPoints:4,runtimeType:null,implementation:"wip"},
  {id:"makeshift_barricade",name:"Makeshift Barricade",category:"furniture",sourceRef:"home_def_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"envelope",name:"Envelope",category:"containers",sourceRef:"book_gen_letter_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"parcel",name:"Parcel",category:"containers",sourceRef:"book_gen_box_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"wire_mesh",name:"Wire Mesh",category:"furniture",sourceRef:"fence_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"wire_mesh",implementation:"implemented"},
  {id:"water_pistol_3_shots",name:"Water Pistol (3 shots)",category:"armoury",sourceRef:"watergun_3_#00",heavy:false,decoration:0,watchPoints:6,runtimeType:null,implementation:"wip"},
  {id:"water_pistol_2_shots",name:"Water Pistol (2 shots)",category:"armoury",sourceRef:"watergun_2_#00",heavy:false,decoration:0,watchPoints:4,runtimeType:"water_pistol",implementation:"implemented"},
  {id:"water_pistol_1_shot",name:"Water Pistol (1 shot)",category:"armoury",sourceRef:"watergun_1_#00",heavy:false,decoration:0,watchPoints:2,runtimeType:"water_pistol",implementation:"implemented"},
  {id:"aqua_splash_5_shots",name:"Aqua-Splash (5 shots)",category:"armoury",sourceRef:"watergun_opt_5_#00",heavy:false,decoration:0,watchPoints:12,runtimeType:null,implementation:"wip"},
  {id:"aqua_splash_4_shots",name:"Aqua-Splash (4 shots)",category:"armoury",sourceRef:"watergun_opt_4_#00",heavy:false,decoration:0,watchPoints:9,runtimeType:null,implementation:"wip"},
  {id:"opened_packet_of_cigarettes",name:"Opened packet of Cigarettes",category:"miscellaneous",sourceRef:"cigs_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"puta_mark_ii_calibrator",name:"PUTA Mark II Calibrator",category:"miscellaneous",sourceRef:"pilegun_upkit_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"battery_launcher_mk_ii_empty",name:"Battery Launcher Mk. II (empty)",category:"armoury",sourceRef:"pilegun_up_empty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"battery_launcher_mk_ii_loaded",name:"Battery Launcher Mk. II (loaded)",category:"armoury",sourceRef:"pilegun_up_#00",heavy:false,decoration:0,watchPoints:11,runtimeType:null,implementation:"wip"},
  {id:"crushed_battery",name:"Crushed Battery",category:"miscellaneous",sourceRef:"pile_broken_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"construction_kit_3",name:"Construction Kit (3)",category:"containers",sourceRef:"rsc_pack_3_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"resource_pack",implementation:"implemented"},
  {id:"construction_kit_2",name:"Construction Kit (2)",category:"containers",sourceRef:"rsc_pack_2_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"resource_pack",implementation:"implemented"},
  {id:"construction_kit_1",name:"Construction Kit (1)",category:"containers",sourceRef:"rsc_pack_1_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"resource_pack",implementation:"implemented"},
  {id:"car_door",name:"Car Door",category:"defences",sourceRef:"car_door_#00",heavy:true,decoration:0,watchPoints:25,runtimeType:null,implementation:"wip"},
  {id:"car_door_incomplete",name:"Car Door (incomplete)",category:"miscellaneous",sourceRef:"car_door_part_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"vial_of_poison",name:"Vial of Poison",category:"miscellaneous",sourceRef:"poison_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"corrosive_liquid",name:"Corrosive Liquid",category:"miscellaneous",sourceRef:"poison_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"poison_gland",implementation:"partial"},
  {id:"shrewd_citizen_s_stash",name:"Shrewd Citizen's Stash",category:"containers",sourceRef:"chest_hero_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"postal_parcel",name:"Postal Parcel",category:"containers",sourceRef:"postal_box_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"lunch_box",name:"Lunch Box",category:"containers",sourceRef:"food_armag_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"handful_of_sweets",name:"Handful of Sweets",category:"food",sourceRef:"food_candies_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"sheet_of_plywood",name:"Sheet of Plywood",category:"miscellaneous",sourceRef:"out_def_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"torch",name:"Torch",category:"defences",sourceRef:"torch_#00",heavy:false,decoration:0,watchPoints:15,runtimeType:"torch",implementation:"implemented"},
  {id:"burnt_out_torch",name:"Burnt out Torch",category:"armoury",sourceRef:"torch_off_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:null,implementation:"wip"},
  {id:"dried_marshmallows",name:"Dried Marshmallows",category:"food",sourceRef:"chama_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"burnt_marshmallows",name:"Burnt Marshmallows",category:"food",sourceRef:"chama_tasty_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"pc_base_unit",name:"PC Base Unit",category:"furniture",sourceRef:"pc_#00",heavy:true,decoration:3,watchPoints:15,runtimeType:"pc_base_unit",implementation:"implemented"},
  {id:"safe",name:"Safe",category:"containers",sourceRef:"safe_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"safe",implementation:"implemented"},
  {id:"encyclopedia",name:"Encyclopedia",category:"miscellaneous",sourceRef:"rp_twin_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"water_cooler_bottle_empty",name:"Water Cooler Bottle (Empty)",category:"miscellaneous",sourceRef:"water_can_empty_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:"water_cooler_bottle",implementation:"partial"},
  {id:"water_cooler_bottle_1_ration",name:"Water Cooler Bottle (1 Ration)",category:"food",sourceRef:"water_can_1_#00",heavy:true,decoration:0,watchPoints:8,runtimeType:"water_cooler_bottle",implementation:"partial"},
  {id:"water_cooler_bottle_2_rations",name:"Water Cooler Bottle (2 Rations)",category:"food",sourceRef:"water_can_2_#00",heavy:true,decoration:0,watchPoints:16,runtimeType:"water_cooler_bottle",implementation:"partial"},
  {id:"water_cooler_bottle_3_rations",name:"Water Cooler Bottle (3 Rations)",category:"food",sourceRef:"water_can_3_#00",heavy:true,decoration:0,watchPoints:24,runtimeType:"water_cooler_bottle",implementation:"partial"},
  {id:"betapropine_5mg_expired",name:"Betapropine 5mg (expired)",category:"pharmacy",sourceRef:"beta_drug_bad_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"betapropine_5mg",name:"Betapropine 5mg",category:"pharmacy",sourceRef:"beta_drug_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"fleshrooms",name:"Fleshrooms",category:"miscellaneous",sourceRef:"fruit_sub_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"sticky_pastry_ball",name:"Sticky Pastry Ball",category:"miscellaneous",sourceRef:"fruit_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"pound_of_flesh",name:"Pound of Flesh",category:"miscellaneous",sourceRef:"flesh_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"grisly_bomb",name:"Grisly Bomb",category:"miscellaneous",sourceRef:"flesh_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"thick_solution",name:"Thick Solution",category:"pharmacy",sourceRef:"pharma_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"fleshroom_puree",name:"Fleshroom Puree",category:"food",sourceRef:"fruit_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"stagnant_water_can",name:"Stagnant Water Can",category:"miscellaneous",sourceRef:"water_cup_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"purified_stagnant_water",name:"Purified Stagnant Water",category:"food",sourceRef:"water_cup_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"banned_citizen_s_note",name:"Banned Citizen's Note",category:"miscellaneous",sourceRef:"banned_note_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bloody_dressing",name:"Bloody Dressing",category:"pharmacy",sourceRef:"infect_poison_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"cursed_cuddly_toy",name:"Cursed Cuddly Toy",category:"furniture",sourceRef:"teddy_#01",heavy:false,decoration:1,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"sawdust_steak",name:"Sawdust Steak",category:"food",sourceRef:"woodsteak_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"second_hand_red_coat",name:"Second-hand Red Coat",category:"miscellaneous",sourceRef:"christmas_suit_1_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"ripped_red_trousers",name:"Ripped Red Trousers",category:"miscellaneous",sourceRef:"christmas_suit_2_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"foul_smelling_red_hat",name:"Foul-smelling Red Hat",category:"miscellaneous",sourceRef:"christmas_suit_3_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"foul_smelling_vintage_suit",name:"Foul-smelling Vintage Suit",category:"miscellaneous",sourceRef:"christmas_suit_full_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"mobile_phone",name:"Mobile Phone",category:"armoury",sourceRef:"iphone_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:null,implementation:"wip"},
  {id:"festering_flesh",name:"Festering Flesh",category:"miscellaneous",sourceRef:"smelly_meat_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"novelty_torch_off",name:"Novelty Torch (off)",category:"furniture",sourceRef:"maglite_off_#00",heavy:false,decoration:5,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"novelty_torch_1_charge",name:"Novelty Torch (1 charge)",category:"furniture",sourceRef:"maglite_1_#00",heavy:false,decoration:5,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"novelty_torch_2_charges",name:"Novelty Torch (2 charges)",category:"furniture",sourceRef:"maglite_2_#00",heavy:false,decoration:5,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"traveller_s_corpse",name:"Traveller's Corpse",category:"food",sourceRef:"cadaver_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"gnawed_corpse",name:"Gnawed Corpse",category:"miscellaneous",sourceRef:"cadaver_remains_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"pine_fresh_smoke_bomb",name:"« Pine Fresh » Smoke Bomb",category:"miscellaneous",sourceRef:"smoke_bomb_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"sand_ball",name:"Sand Ball",category:"miscellaneous",sourceRef:"sand_ball_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"construction_blueprint_common",name:"Construction Blueprint (common)",category:"miscellaneous",sourceRef:"bplan_c_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"common_blueprint",implementation:"implemented"},
  {id:"construction_blueprint_uncommon",name:"Construction Blueprint (uncommon)",category:"miscellaneous",sourceRef:"bplan_u_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"uncommon_blueprint",implementation:"implemented"},
  {id:"construction_blueprint_rare",name:"Construction Blueprint (rare)",category:"miscellaneous",sourceRef:"bplan_r_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"rare_blueprint",implementation:"implemented"},
  {id:"construction_blueprint_very_rare",name:"Construction Blueprint (very rare!)",category:"miscellaneous",sourceRef:"bplan_e_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"very_rare_blueprint",implementation:"implemented"},
  {id:"architect_s_chest",name:"Architect's Chest",category:"containers",sourceRef:"bplan_box_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"sealed_architect_s_chest",name:"Sealed Architect's Chest",category:"containers",sourceRef:"bplan_box_e_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"egg",name:"Egg",category:"food",sourceRef:"egg_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"overly_tempting_apple",name:"Overly tempting apple",category:"food",sourceRef:"apple_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"exploding_grapefruit",name:"Exploding Grapefruit",category:"armoury",sourceRef:"boomfruit_#00",heavy:false,decoration:0,watchPoints:12,runtimeType:null,implementation:"wip"},
  {id:"worn_leather_bag",name:"Worn Leather Bag",category:"miscellaneous",sourceRef:"bplan_drop_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"worn_leather_bag",implementation:"implemented"},
  {id:"magnetic_key",name:"Magnetic Key",category:"miscellaneous",sourceRef:"magneticKey_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bump_key",name:"Bump Key",category:"miscellaneous",sourceRef:"bumpKey_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bottle_opener",name:"Bottle Opener",category:"miscellaneous",sourceRef:"classicKey_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"magnetic_key_blank",name:"Magnetic Key Blank",category:"miscellaneous",sourceRef:"prints_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bump_key_blank",name:"Bump Key Blank",category:"miscellaneous",sourceRef:"prints_#01",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bottle_opener_blank",name:"Bottle Opener Blank",category:"miscellaneous",sourceRef:"prints_#02",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"ghoul_vaccine",name:"Ghoul Vaccine",category:"pharmacy",sourceRef:"vagoul_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"hotel_blueprint_uncommon",name:"Hotel Blueprint (uncommon)",category:"miscellaneous",sourceRef:"hbplan_u_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"hotel_blueprint_rare",name:"Hotel Blueprint (rare)",category:"miscellaneous",sourceRef:"hbplan_r_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"hotel_blueprint_very_rare",name:"Hotel Blueprint (very rare!)",category:"miscellaneous",sourceRef:"hbplan_e_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bunker_blueprint_uncommon",name:"Bunker Blueprint (uncommon)",category:"miscellaneous",sourceRef:"bbplan_u_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bunker_blueprint_rare",name:"Bunker Blueprint (rare)",category:"miscellaneous",sourceRef:"bbplan_r_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bunker_blueprint_very_rare",name:"Bunker Blueprint (very rare!)",category:"miscellaneous",sourceRef:"bbplan_e_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"hospital_blueprint_uncommon",name:"Hospital Blueprint (uncommon)",category:"miscellaneous",sourceRef:"mbplan_u_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"hospital_blueprint_rare",name:"Hospital Blueprint (rare)",category:"miscellaneous",sourceRef:"mbplan_r_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"hospital_blueprint_very_rare",name:"Hospital Blueprint (very rare!)",category:"miscellaneous",sourceRef:"mbplan_e_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"lost_soul",name:"Lost Soul",category:"miscellaneous",sourceRef:"soul_blue_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"tortured_soul",name:"Tortured Soul",category:"miscellaneous",sourceRef:"soul_red_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"weak_soul",name:"Weak Soul",category:"miscellaneous",sourceRef:"soul_blue_#01",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"mug_of_lukewarm_liquid",name:"Mug of lukewarm liquid",category:"food",sourceRef:"fest_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"sandy_pretzel",name:"Sandy Pretzel",category:"food",sourceRef:"bretz_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"mangy_dachshund",name:"Mangy Dachshund",category:"defences",sourceRef:"tekel_#00",heavy:false,decoration:0,watchPoints:18,runtimeType:null,implementation:"wip"},
  {id:"stake_launcher",name:"Stake Launcher",category:"armoury",sourceRef:"rlaunc_#00",heavy:true,decoration:0,watchPoints:30,runtimeType:null,implementation:"wip"},
  {id:"kalashni_splash",name:"Kalashni-Splash",category:"armoury",sourceRef:"kalach_#00",heavy:true,decoration:0,watchPoints:24,runtimeType:null,implementation:"wip"},
  {id:"hastily_built_desk",name:"Hastily-built Desk",category:"furniture",sourceRef:"bureau_#00",heavy:true,decoration:2,watchPoints:20,runtimeType:null,implementation:"wip"},
  {id:"empty_vending_machine",name:"Empty Vending Machine",category:"furniture",sourceRef:"distri_#00",heavy:true,decoration:4,watchPoints:25,runtimeType:null,implementation:"wip"},
  {id:"santa_s_reindeer",name:"Santa's Reindeer",category:"miscellaneous",sourceRef:"renne_#00",heavy:true,decoration:0,watchPoints:25,runtimeType:null,implementation:"wip"},
  {id:"easter_egg",name:"Easter Egg",category:"miscellaneous",sourceRef:"paques_#00",heavy:false,decoration:0,watchPoints:18,runtimeType:null,implementation:"wip"},
  {id:"collector_pins",name:"Collector Pins",category:"armoury",sourceRef:"badge_#00",heavy:false,decoration:0,watchPoints:14,runtimeType:null,implementation:"wip"},
  {id:"kalashni_splash_empty",name:"Kalashni-Splash (empty)",category:"armoury",sourceRef:"kalach_#01",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"wire_reel",name:"Wire Reel",category:"resources",sourceRef:"wire_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"wire_reel",implementation:"implemented"},
  {id:"empty_oil_can",name:"Empty Oil Can",category:"resources",sourceRef:"oilcan_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"empty_oil_can",implementation:"implemented"},
  {id:"convex_lens",name:"Convex Lens",category:"resources",sourceRef:"lens_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"convex_lens",implementation:"implemented"},
  {id:"furious_kitten_partially_digested",name:"Furious Kitten (partially digested)",category:"furniture",sourceRef:"angryc_#00",heavy:false,decoration:1,watchPoints:18,runtimeType:null,implementation:"wip"},
  {id:"claymore_mine",name:"Claymore Mine",category:"armoury",sourceRef:"claymo_#00",heavy:false,decoration:0,watchPoints:40,runtimeType:"claymore",implementation:"implemented"},
  {id:"laser_diode",name:"Laser Diode",category:"resources",sourceRef:"diode_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"laser_diode",implementation:"implemented"},
  {id:"makeshift_guitar",name:"Makeshift Guitar",category:"furniture",sourceRef:"guitar_#00",heavy:false,decoration:6,watchPoints:10,runtimeType:"guitar",implementation:"partial"},
  {id:"lsd",name:"LSD",category:"pharmacy",sourceRef:"lsd_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"burning_laser_pointer_4_charges",name:"Burning Laser Pointer (4 charges)",category:"armoury",sourceRef:"lpoint4_#00",heavy:false,decoration:0,watchPoints:20,runtimeType:null,implementation:"wip"},
  {id:"burning_laser_pointer_3_charges",name:"Burning Laser Pointer (3 charges)",category:"armoury",sourceRef:"lpoint3_#00",heavy:false,decoration:0,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"burning_laser_pointer_2_charges",name:"Burning Laser Pointer (2 charges)",category:"armoury",sourceRef:"lpoint2_#00",heavy:false,decoration:0,watchPoints:10,runtimeType:null,implementation:"wip"},
  {id:"burning_laser_pointer_1_charge",name:"Burning Laser Pointer (1 charge)",category:"armoury",sourceRef:"lpoint1_#00",heavy:false,decoration:0,watchPoints:5,runtimeType:null,implementation:"wip"},
  {id:"burning_laser_pointer_empty",name:"Burning Laser Pointer (Empty)",category:"armoury",sourceRef:"lpoint_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"telescope",name:"Telescope",category:"resources",sourceRef:"scope_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"telescope",implementation:"implemented"},
  {id:"impersonal_exploding_doormat",name:"Impersonal Exploding Doormat",category:"furniture",sourceRef:"trapma_#00",heavy:false,decoration:5,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"chuck_figurine",name:"Chuck Figurine",category:"furniture",sourceRef:"chudol_#00",heavy:false,decoration:15,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"little_book_of_calm",name:"Little Book of Calm",category:"pharmacy",sourceRef:"lilboo_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bag_of_damp_grass",name:"Bag of Damp Grass",category:"resources",sourceRef:"ryebag_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"bag_of_damp_grass",implementation:"implemented"},
  {id:"ergot_fungus",name:"Ergot Fungus",category:"food",sourceRef:"fungus_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"ergot_homebrew",name:"Ergot Homebrew",category:"food",sourceRef:"hmbrew_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"cursed_hifi",name:"Cursed HiFi",category:"furniture",sourceRef:"hifiev_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"phil_collins_cd",name:"Phil Collins CD",category:"furniture",sourceRef:"cdphil_#00",heavy:false,decoration:1,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"earplugs",name:"Earplugs",category:"resources",sourceRef:"bquies_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"earplugs",implementation:"partial"},
  {id:"broken_staff",name:"Broken Staff",category:"resources",sourceRef:"staff_#01",heavy:false,decoration:0,watchPoints:0,runtimeType:"broken_staff",implementation:"implemented"},
  {id:"britney_spears_cd",name:"Britney Spears CD",category:"furniture",sourceRef:"cdbrit_#00",heavy:false,decoration:3,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"best_of_the_king_cd",name:"Best of The King CD",category:"furniture",sourceRef:"cdelvi_#00",heavy:false,decoration:7,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"rock_n_roll_hifi",name:"Rock n Roll HiFi",category:"furniture",sourceRef:"dfhifi_#00",heavy:true,decoration:10,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"anti_personnel_hifi",name:"Anti-personnel HiFi",category:"furniture",sourceRef:"dfhifi_#01",heavy:true,decoration:10,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"schrodinger_s_box",name:"Schrödinger's Box",category:"containers",sourceRef:"catbox_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"psychadelic_spiritual_counsel",name:"Psychadelic Spiritual Counsel",category:"miscellaneous",sourceRef:"chkspk_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"fat_serpent",name:"Fat Serpent",category:"miscellaneous",sourceRef:"pet_snake2_#00",heavy:true,decoration:0,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"christmas_present_3",name:"Christmas Present (3)",category:"containers",sourceRef:"chest_christmas_3_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"christmas_present_2",name:"Christmas Present (2)",category:"containers",sourceRef:"chest_christmas_2_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"christmas_present_1",name:"Christmas Present (1)",category:"containers",sourceRef:"chest_christmas_1_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"suspicious_looking_plum_juice",name:"Suspicious looking plum juice",category:"food",sourceRef:"omg_this_will_kill_you_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"label",name:"Label",category:"miscellaneous",sourceRef:"rp_scroll_#01",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"town_uniform",name:"Town Uniform",category:"miscellaneous",sourceRef:"basic_suit_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"dirty_uniform",name:"Dirty Uniform",category:"miscellaneous",sourceRef:"basic_suit_dirt_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"camouflage_vest",name:"Camouflage Vest",category:"miscellaneous",sourceRef:"vest_on_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"camouflage_vest_not_equipped",name:"Camouflage Vest (not equipped!)",category:"miscellaneous",sourceRef:"vest_off_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"small_spade",name:"Small Spade",category:"miscellaneous",sourceRef:"pelle_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"three_legged_labradoodle",name:"Three-legged Labradoodle",category:"miscellaneous",sourceRef:"tamed_pet_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"well_fed_labradoodle",name:"Well fed Labradoodle",category:"miscellaneous",sourceRef:"tamed_pet_drug_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"tired_labradoodle",name:"Tired Labradoodle",category:"miscellaneous",sourceRef:"tamed_pet_off_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"survival_book",name:"Survival Book",category:"miscellaneous",sourceRef:"surv_book_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"handyman_s_toolbelt",name:"Handyman's Toolbelt",category:"miscellaneous",sourceRef:"keymol_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"riot_shield",name:"Riot Shield",category:"miscellaneous",sourceRef:"shield_#00",heavy:false,decoration:0,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"voodoo_mask",name:"Voodoo Mask",category:"miscellaneous",sourceRef:"shaman_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"super_fuzz_powder",name:"Super-Fuzz Powder",category:"furniture",sourceRef:"firework_powder_#00",heavy:false,decoration:5,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"firework_launch_tube",name:"Firework Launch Tube",category:"furniture",sourceRef:"firework_tube_#00",heavy:true,decoration:2,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"box_of_fireworks",name:"Box of Fireworks",category:"furniture",sourceRef:"firework_box_#00",heavy:true,decoration:3,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"carved_soft_pumpkin",name:"Carved Soft Pumpkin",category:"furniture",sourceRef:"pumpkin_off_#00",heavy:true,decoration:5,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"lit_pumpkin",name:"Lit Pumpkin",category:"defences",sourceRef:"pumpkin_on_#00",heavy:false,decoration:15,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"crow_garland",name:"Crow garland",category:"furniture",sourceRef:"xmas_gift_#00",heavy:false,decoration:2,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"broken_staff_variant_2",name:"Broken Staff",category:"resources",sourceRef:"staff2_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"broken_staff",implementation:"implemented"},
  {id:"vodka_marinostov",name:"Vodka Marinostov",category:"food",sourceRef:"vodka_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:"vodka_marinostov",implementation:"implemented"},
  {id:"mystic_potion",name:"Mystic Potion",category:"food",sourceRef:"potion_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"pre_war_camera",name:"Pre-war camera",category:"miscellaneous",sourceRef:"photo_3_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"pre_war_camera_variant_2",name:"Pre-war camera",category:"miscellaneous",sourceRef:"photo_2_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"pre_war_camera_variant_3",name:"Pre-war camera",category:"miscellaneous",sourceRef:"photo_1_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"pre_war_camera_variant_4",name:"Pre-war camera",category:"miscellaneous",sourceRef:"photo_off_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"powerful_soul",name:"Powerful Soul",category:"miscellaneous",sourceRef:"soul_yellow_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"crow_elf",name:"Crow elf",category:"food",sourceRef:"food_xmas_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"chocolate_log",name:"Chocolate log",category:"food",sourceRef:"wood_xmas_#00",heavy:true,decoration:8,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"green_imp_suit",name:"Green Imp Suit",category:"miscellaneous",sourceRef:"leprechaun_suit_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"unrecognisable_remains",name:"Unrecognisable Remains",category:"miscellaneous",sourceRef:"broken_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"handful_of_bullets",name:"Handful of Bullets",category:"miscellaneous",sourceRef:"bullets_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"gift_parcel",name:"Gift Parcel",category:"containers",sourceRef:"postal_box_#01",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"large_gift_parcel",name:"Large Gift Parcel",category:"containers",sourceRef:"postal_box_xl_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"christmas_candy",name:"Christmas candy",category:"food",sourceRef:"christmas_candy_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"screaming_alarm_clock_incomplete",name:"Screaming Alarm Clock (incomplete)",category:"miscellaneous",sourceRef:"alarm_off_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"screaming_alarm_clock_ready",name:"Screaming Alarm Clock (ready)",category:"miscellaneous",sourceRef:"alarm_on_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"soft_pumpkin",name:"Soft Pumpkin",category:"miscellaneous",sourceRef:"pumpkin_raw_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"primitive_hurling_stick",name:"Primitive Hurling Stick",category:"armoury",sourceRef:"hurling_stick_#00",heavy:false,decoration:0,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"sticky_pint",name:"Sticky Pint",category:"food",sourceRef:"guiness_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"black_neck_ooze",name:"Black Neck Ooze",category:"pharmacy",sourceRef:"april_drug_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"toxin",name:"Toxin",category:"miscellaneous",sourceRef:"infect_poison_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"impressive_pumpkin",name:"Impressive Pumpkin",category:"food",sourceRef:"pumpkin_tasty_#00",heavy:true,decoration:0,watchPoints:15,runtimeType:null,implementation:"wip"},
  {id:"first_aid_kit",name:"First Aid Kit",category:"pharmacy",sourceRef:"medic_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"hanging_crow_garland",name:"Hanging Crow garland",category:"furniture",sourceRef:"xmas_gift_#01",heavy:false,decoration:5,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"no_labradoodle",name:"No labradoodle",category:"miscellaneous",sourceRef:"tamed_pet_gone_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"screaming_alarm_clock_1_charge",name:"Screaming Alarm Clock (1 charge)",category:"miscellaneous",sourceRef:"alarm_1_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"screaming_alarm_clock_2_charges",name:"Screaming Alarm Clock (2 charges)",category:"miscellaneous",sourceRef:"alarm_2_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"screaming_alarm_clock_3_charges",name:"Screaming Alarm Clock (3 charges)",category:"miscellaneous",sourceRef:"alarm_3_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"magnetic_key_instant_blank",name:"Magnetic Key Instant Blank",category:"food",sourceRef:"noodle_prints_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bump_key_instant_blank",name:"Bump Key Instant Blank",category:"food",sourceRef:"noodle_prints_#01",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bottle_opener_instant_blank",name:"Bottle Opener Instant Blank",category:"food",sourceRef:"noodle_prints_#02",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"worn_out_sports_shoes",name:"Worn-out sports shoes",category:"miscellaneous",sourceRef:"shoe_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"bicycle_without_handlebars",name:"Bicycle without handlebars",category:"miscellaneous",sourceRef:"bike_part_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"mountain_bike",name:"Mountain bike",category:"miscellaneous",sourceRef:"bike_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"flag",name:"Flag",category:"miscellaneous",sourceRef:"flag_#00",heavy:false,decoration:5,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"football",name:"Football",category:"miscellaneous",sourceRef:"soccer_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"burst_football",name:"Burst Football",category:"miscellaneous",sourceRef:"soccer_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"quantum_energy",name:"Quantum Energy",category:"food",sourceRef:"quantum_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"pre_war_camera_variant_5",name:"Pre-war camera",category:"miscellaneous",sourceRef:"photo_4_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"cello_case",name:"Cello case",category:"containers",sourceRef:"cello_box_#00",heavy:true,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"apple",name:"Apple",category:"food",sourceRef:"apple_blue_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"improvised_hacksaw",name:"Improvised Hacksaw",category:"miscellaneous",sourceRef:"saw_tool_temp_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"fistful_of_insects",name:"Fistful of insects",category:"food",sourceRef:"moldy_food_subpart_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"seasonned_fistful_of_insects",name:"Seasonned fistful of insects",category:"food",sourceRef:"moldy_food_spicy_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"larvae_jam",name:"Larvae Jam",category:"food",sourceRef:"moldy_food_part_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"crawling_crumble",name:"Crawling crumble",category:"food",sourceRef:"moldy_food_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"creepy_mask",name:"Creepy Mask",category:"miscellaneous",sourceRef:"scary_mask_#00",heavy:false,decoration:5,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"riot_shield_strapped",name:"Riot Shield (strapped)",category:"miscellaneous",sourceRef:"shield_off_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
  {id:"ball_of_debris",name:"Ball of debris",category:"miscellaneous",sourceRef:"broken_ball_#00",heavy:false,decoration:0,watchPoints:0,runtimeType:null,implementation:"wip"},
]

export type ItemSourceCatalogId=(typeof ITEM_SOURCE_CATALOG)[number]['id']

export const ITEM_SOURCE_CATALOG_BY_ID:ReadonlyMap<string,ItemSourceCatalogEntry>=new Map(ITEM_SOURCE_CATALOG.map((entry)=>[entry.id,entry]))
export const ITEM_SOURCE_CATALOG_BY_REF:ReadonlyMap<string,ItemSourceCatalogEntry>=new Map(ITEM_SOURCE_CATALOG.map((entry)=>[entry.sourceRef,entry]))

export function itemSourceCatalogStatusCounts():Record<ItemImplementationStatus,number>{
  const counts:Record<ItemImplementationStatus,number>={implemented:0,partial:0,wip:0}
  for(const entry of ITEM_SOURCE_CATALOG)counts[entry.implementation]+=1
  return counts
}
